const tesdaSkillsCertsTypes = [
  { value: '2D ANIMATION NC III', label: '2D ANIMATION NC III' },
  {
    value: '2D ANIMATION NC III - MOBILE TRAINING PROGRAM',
    label: '2D ANIMATION NC III - MOBILE TRAINING PROGRAM',
  },
  {
    value: '2D GAME ART DEVELOPMENT NC III',
    label: '2D GAME ART DEVELOPMENT NC III',
  },
  { value: '3D ANIMATION NC III', label: '3D ANIMATION NC III' },
  {
    value: '3D GAME ART DEVELOPMENT NC III',
    label: '3D GAME ART DEVELOPMENT NC III',
  },
  {
    value: '5-AXIS CNC MACHINE OPERATION NC III',
    label: '5-AXIS CNC MACHINE OPERATION NC III',
  },
  {
    value: 'ABLE SEAFARER DECK NC II (II-5)',
    label: 'ABLE SEAFARER DECK NC II (II-5)',
  },
  {
    value: 'ABLE SEAFARER ENGINE NC II (III-5)',
    label: 'ABLE SEAFARER ENGINE NC II (III-5)',
  },
  { value: 'AGRICULTURAL CROPS NC I', label: 'AGRICULTURAL CROPS NC I' },
  {
    value: 'AGRICULTURAL CROPS PRODUCTION NC II',
    label: 'AGRICULTURAL CROPS PRODUCTION NC II',
  },
  {
    value: 'AGRICULTURAL CROPS PRODUCTION NC III',
    label: 'AGRICULTURAL CROPS PRODUCTION NC III',
  },
  {
    value: 'AGRICULTURAL MACHINERY OPERATION NC II',
    label: 'AGRICULTURAL MACHINERY OPERATION NC II',
  },
  {
    value: 'AGRICULTURAL MACHINERY SERVICING (4-WHEEL TRACTOR) NC III',
    label: 'AGRICULTURAL MACHINERY SERVICING (4-WHEEL TRACTOR) NC III',
  },
  { value: 'AGROENTERPRENEURSHIP NC II', label: 'AGROENTERPRENEURSHIP NC II' },
  {
    value: 'AGROENTERPRENEURSHIP NC III',
    label: 'AGROENTERPRENEURSHIP NC III',
  },
  { value: 'AGROENTERPRENEURSHIP NC IV', label: 'AGROENTERPRENEURSHIP NC IV' },
  { value: 'AIR DUCT SERVICING NCII', label: 'AIR DUCT SERVICING NCII' },
  {
    value: 'ANIMAL HEALTH CARE AND MANAGEMENT NC III',
    label: 'ANIMAL HEALTH CARE AND MANAGEMENT NC III',
  },
  {
    value: 'ANIMAL PRODUCTION (POULTRY-CHICKEN) NC II',
    label: 'ANIMAL PRODUCTION (POULTRY-CHICKEN) NC II',
  },
  {
    value: 'ANIMAL PRODUCTION (RUMINANTS) NC II',
    label: 'ANIMAL PRODUCTION (RUMINANTS) NC II',
  },
  {
    value: 'ANIMAL PRODUCTION (SWINE) NCII',
    label: 'ANIMAL PRODUCTION (SWINE) NCII',
  },
  { value: 'ANIMATION NC II', label: 'ANIMATION NC II' },
  {
    value: 'ANIMATION NC II - MOBILE TRAINING PROGRAM',
    label: 'ANIMATION NC II - MOBILE TRAINING PROGRAM',
  },
  { value: 'AQUACULTURE NC II', label: 'AQUACULTURE NC II' },
  {
    value: 'ARTIFICIAL INSEMINATION (LARGE RUMINANTS) NC II',
    label: 'ARTIFICIAL INSEMINATION (LARGE RUMINANTS) NC II',
  },
  {
    value: 'ARTIFICIAL INSEMINATION (SWINE) NC II',
    label: 'ARTIFICIAL INSEMINATION (SWINE) NC II',
  },
  {
    value: 'ATTRACTIONS AND THEME PARKS NC II',
    label: 'ATTRACTIONS AND THEME PARKS NC II',
  },
  {
    value: 'AUDIO PRODUCTION SERVICES NC I',
    label: 'AUDIO PRODUCTION SERVICES NC I',
  },
  {
    value: 'AUTO BODY PAINTING FINISHING NC I',
    label: 'AUTO BODY PAINTING FINISHING NC I',
  },
  {
    value: 'AUTO BODY PAINTING FINISHING NC II',
    label: 'AUTO BODY PAINTING FINISHING NC II',
  },
  {
    value: 'AUTO BODY PAINTING FINISHING NC III',
    label: 'AUTO BODY PAINTING FINISHING NC III',
  },
  {
    value: 'AUTO ENGINE REBUILDING NC II',
    label: 'AUTO ENGINE REBUILDING NC II',
  },
  {
    value: 'AUTOMOTIVE BODY REPAIRING NC II',
    label: 'AUTOMOTIVE BODY REPAIRING NC II',
  },
  {
    value: 'AUTOMOTIVE ELECTRICAL ASSEMBLY NC II',
    label: 'AUTOMOTIVE ELECTRICAL ASSEMBLY NC II',
  },
  {
    value: 'AUTOMOTIVE ELECTRICAL ASSEMBLY NC III',
    label: 'AUTOMOTIVE ELECTRICAL ASSEMBLY NC III',
  },
  { value: 'AUTOMOTIVE SERVICING NC II', label: 'AUTOMOTIVE SERVICING NC II' },
  {
    value: 'AUTOMOTIVE MECHANICAL ASSEMBLY NC II',
    label: 'AUTOMOTIVE MECHANICAL ASSEMBLY NC II',
  },
  { value: 'AUTOMOTIVE SERVICING NC I', label: 'AUTOMOTIVE SERVICING NC I' },
  {
    value: 'AUTOMOTIVE SERVICING NC I - MOBILE TRAINING PROGRAM',
    label: 'AUTOMOTIVE SERVICING NC I - MOBILE TRAINING PROGRAM',
  },
  {
    value: 'AUTOMOTIVE SERVICING NC II - MOBILE TRAINING PROGRAM',
    label: 'AUTOMOTIVE SERVICING NC II - MOBILE TRAINING PROGRAM',
  },
  {
    value: 'AUTOMOTIVE SERVICING NC III',
    label: 'AUTOMOTIVE SERVICING NC III',
  },
  { value: 'AUTOMOTIVE SERVICING NC IV', label: 'AUTOMOTIVE SERVICING NC IV' },
  {
    value: 'AUTOMOTIVE WIRING HARNESS ASSEMBLY NC II',
    label: 'AUTOMOTIVE WIRING HARNESS ASSEMBLY NC II',
  },
  {
    value: 'BAMBOO PROCESSING (ENGINEERED-BAMBOO) NC II',
    label: 'BAMBOO PROCESSING (ENGINEERED-BAMBOO) NC II',
  },
  { value: 'BAMBOO PRODUCTION NC II', label: 'BAMBOO PRODUCTION NC II' },
  {
    value: 'BARANGAY HEALTH SERVICES NC II',
    label: 'BARANGAY HEALTH SERVICES NC II',
  },
  {
    value: 'BARANGAY HEALTH SERVICES NC II - MOBILE TRAINING PROGRAM',
    label: 'BARANGAY HEALTH SERVICES NC II - MOBILE TRAINING PROGRAM',
  },
  { value: 'BARBERING NC II', label: 'BARBERING NC II' },
  { value: 'BARISTA NC II', label: 'BARISTA NC II' },
  { value: 'BARTENDING NC II', label: 'BARTENDING NC II' },
  {
    value: 'BEAUTY CARE (SKIN CARE) NC II',
    label: 'BEAUTY CARE (SKIN CARE) NC II',
  },
  { value: 'BEAUTY CARE NC II', label: 'BEAUTY CARE NC II' },
  { value: 'BEAUTY CARE NC III', label: 'BEAUTY CARE NC III' },
  {
    value: 'BEAUTY CARE SERVICES (NAIL CARE) NC II - NEW',
    label: 'BEAUTY CARE SERVICES (NAIL CARE) NC II - NEW',
  },
  {
    value: 'BEAUTY CARE SERVICES (NAIL CARE) NC III - NEW',
    label: 'BEAUTY CARE SERVICES (NAIL CARE) NC III - NEW',
  },
  {
    value: 'BIOMEDICAL EQUIPMENT SERVICES NCII',
    label: 'BIOMEDICAL EQUIPMENT SERVICES NCII',
  },
  { value: 'BOOKKEEPING NC III', label: 'BOOKKEEPING NC III' },
  {
    value: 'BREAD AND PASTRY PRODUCTION NC II',
    label: 'BREAD AND PASTRY PRODUCTION NC II',
  },
  {
    value: 'BROADBAND INSTALLATION (FIXED WIRELESS SYSTEMS) NC II',
    label: 'BROADBAND INSTALLATION (FIXED WIRELESS SYSTEMS) NC II',
  },
  {
    value: 'CABLE TV INSTALLATION NC II',
    label: 'CABLE TV INSTALLATION NC II',
  },
  {
    value: 'CHEMICAL PROCESS OPERATIONS NC III',
    label: 'CHEMICAL PROCESS OPERATIONS NC III',
  },
  { value: 'CAREGIVING NC II', label: 'CAREGIVING NC II' },
  { value: 'CARPENTRY NC II', label: 'CARPENTRY NC II' },
  {
    value: 'CARPENTRY NC II - MOBILE TRAINING PROGRAM',
    label: 'CARPENTRY NC II - MOBILE TRAINING PROGRAM',
  },
  { value: 'CARPENTRY NC III', label: 'CARPENTRY NC III' },
  {
    value: 'CATV OPERATION & MAINTENANCE NC III',
    label: 'CATV OPERATION & MAINTENANCE NC III',
  },
  {
    value: 'CHEMICAL PROCESS OPERATIONS NC III',
    label: 'CHEMICAL PROCESS OPERATIONS NC III',
  },
  {
    value: 'CNC ELECTRICAL DISCHARGE MACHINE (EDM)-WIRE CUT OPERATION NC III',
    label: 'CNC ELECTRICAL DISCHARGE MACHINE (EDM)-WIRE CUT OPERATION NC III',
  },
  {
    value: 'CNC LATHE MACHINE OPERATION NC II',
    label: 'CNC LATHE MACHINE OPERATION NC II',
  },
  {
    value: 'CNC LATHE MACHINE OPERATION NC III',
    label: 'CNC LATHE MACHINE OPERATION NC III',
  },
  {
    value: 'CNC MILLING MACHINE OPERATION NC II',
    label: 'CNC MILLING MACHINE OPERATION NC II',
  },
  {
    value: 'CNC MILLING MACHINE OPERATION NC III',
    label: 'CNC MILLING MACHINE OPERATION NC III',
  },
  { value: 'COMMERCIAL COOKING NC III', label: 'COMMERCIAL COOKING NC III' },
  { value: 'COMMERCIAL COOKING NC IV', label: 'COMMERCIAL COOKING NC IV' },
  {
    value: 'COMPUTER SYSTEMS SERVICING NC II',
    label: 'COMPUTER SYSTEMS SERVICING NC II',
  },
  {
    value: 'CONSTRUCTION LIFT PASSENGER MATERIAL ELEVATOR OPERATION NC II',
    label: 'CONSTRUCTION LIFT PASSENGER MATERIAL ELEVATOR OPERATION NC II',
  },
  {
    value: 'CONSTRUCTION PAINTING NC II',
    label: 'CONSTRUCTION PAINTING NC II',
  },
  {
    value: 'CONSTRUCTION PAINTING NC III',
    label: 'CONSTRUCTION PAINTING NC III',
  },
  {
    value: 'CONSUMER ELECTRONICS NC III',
    label: 'CONSUMER ELECTRONICS NC III',
  },
  { value: 'CONSUMER ELECTRONICS NC IV', label: 'CONSUMER ELECTRONICS NC IV' },
  {
    value: 'CONTACT CENTER SERVICES NC II',
    label: 'CONTACT CENTER SERVICES NC II',
  },
  { value: 'COOKERY NC II', label: 'COOKERY NC II' },
  { value: 'CUSTOMER SERVICES NC II', label: 'CUSTOMER SERVICES NC II' },
  { value: 'DENTAL HYGIENE LEVEL IV', label: 'DENTAL HYGIENE LEVEL IV' },
  {
    value:
      'DENTAL LABORATORY TECHNOLOGY SERVICES (FIXED DENTURES/RESTORATIONS) NC II',
    label:
      'DENTAL LABORATORY TECHNOLOGY SERVICES (FIXED DENTURES/RESTORATIONS) NC II',
  },
  {
    value: 'DENTAL LABORATORY TECHNOLOGY SERVICES (REMOVABLE) NC II',
    label: 'DENTAL LABORATORY TECHNOLOGY SERVICES (REMOVABLE) NC II',
  },
  {
    value: 'DENTAL LABORATORY TECHNOLOGY SERVICES NC I',
    label: 'DENTAL LABORATORY TECHNOLOGY SERVICES NC I',
  },
  { value: 'DENTAL TECHNOLOGY NC IV', label: 'DENTAL TECHNOLOGY NC IV' },
  { value: 'DIE DESIGNING NC IV', label: 'DIE DESIGNING NC IV' },
  {
    value: 'DIESEL POWER PLANT MAINTENANCE NC III',
    label: 'DIESEL POWER PLANT MAINTENANCE NC III',
  },
  {
    value: 'DIESEL POWER PLANT OPERATION & MAINTENANCE NC II',
    label: 'DIESEL POWER PLANT OPERATION & MAINTENANCE NC II',
  },
  {
    value: 'DIESEL POWER PLANT OPERATION & MAINTENANCE NC III',
    label: 'DIESEL POWER PLANT OPERATION & MAINTENANCE NC III',
  },
  { value: 'DOMESTIC WORK NC II', label: 'DOMESTIC WORK NC II' },
  { value: 'DRESSMAKING (CASUAL) NC II', label: 'DRESSMAKING (CASUAL) NC II' },
  {
    value: 'DRIVING (ARTICULATED VEHICLE) NC III',
    label: 'DRIVING (ARTICULATED VEHICLE) NC III',
  },
  {
    value: 'DRIVING (PASSENGER BUS/STRAIGHT TRUCK) NC III',
    label: 'DRIVING (PASSENGER BUS/STRAIGHT TRUCK) NC III',
  },
  { value: 'DRIVING NC II', label: 'DRIVING NC II' },
  {
    value: 'DRYING AND MILLING PLANT SERVICING NC III',
    label: 'DRYING AND MILLING PLANT SERVICING NC III',
  },
  {
    value: 'ELECTRIC DISCHARGE MACHINE (EDM)-SINKING OPERATION NC II',
    label: 'ELECTRIC DISCHARGE MACHINE (EDM)-SINKING OPERATION NC II',
  },
  {
    value: 'ELECTRIC POWER DISTRIBUTION LINE CONSTRUCTION NC II',
    label: 'ELECTRIC POWER DISTRIBUTION LINE CONSTRUCTION NC II',
  },
  {
    value:
      'ELECTRONICS-SEMICONDUCTORS PRODUCTION LINE MACHINE SERVICING NC III',
    label:
      'ELECTRONICS-SEMICONDUCTORS PRODUCTION LINE MACHINE SERVICING NC III',
  },
  {
    value: 'ELECTRICAL INSTALLATION & MAINTENANCE NC II',
    label: 'ELECTRICAL INSTALLATION & MAINTENANCE NC II',
  },
  {
    value: 'ELECTRICAL INSTALLATION & MAINTENANCE NC III',
    label: 'ELECTRICAL INSTALLATION & MAINTENANCE NC III',
  },
  {
    value: 'ELECTRICAL POWER DISTRIBUTION OPERATION AND MAINTENANCE NC III',
    label: 'ELECTRICAL POWER DISTRIBUTION OPERATION AND MAINTENANCE NC III',
  },
  {
    value: 'ELECTRICAL POWER DISTRIBUTION OPERATION AND MAINTENANCE NC IV',
    label: 'ELECTRICAL POWER DISTRIBUTION OPERATION AND MAINTENANCE NC IV',
  },
  {
    value: 'ELECTRONIC PRODUCTS ASSEMBLY AND SERVICING NC II',
    label: 'ELECTRONIC PRODUCTS ASSEMBLY AND SERVICING NC II',
  },
  {
    value: 'ELECTRONICS BACK-END OPERATION NC II',
    label: 'ELECTRONICS BACK-END OPERATION NC II',
  },
  {
    value: 'ELECTRONICS FRONT-OF-LINE OPERATION NC II',
    label: 'ELECTRONICS FRONT-OF-LINE OPERATION NC II',
  },
  {
    value:
      'ELECTRONICS-SEMICONDUCTORS PRODUCTION LINE MACHINE SERVICING NC III',
    label:
      'ELECTRONICS-SEMICONDUCTORS PRODUCTION LINE MACHINE SERVICING NC III',
  },
  {
    value: 'EMERGENCY MEDICAL SERVICES NC II',
    label: 'EMERGENCY MEDICAL SERVICES NC II',
  },
  {
    value: 'EVENTS MANAGEMENT SERVICES NC III',
    label: 'EVENTS MANAGEMENT SERVICES NC III',
  },
  {
    value: 'FASHION DESIGN (APPAREL) NC III - NEW',
    label: 'FASHION DESIGN (APPAREL) NC III - NEW',
  },
  { value: 'FISH CAPTURE NC I', label: 'FISH CAPTURE NC I' },
  { value: 'FISH CAPTURE NC II', label: 'FISH CAPTURE NC II' },
  {
    value: 'FISH PRODUCTS PACKAGING NC II',
    label: 'FISH PRODUCTS PACKAGING NC II',
  },
  {
    value: 'FISHING GEAR REPAIR AND MAINTENANCE NC III',
    label: 'FISHING GEAR REPAIR AND MAINTENANCE NC III',
  },
  {
    value: 'FISHPORTWHARF OPERATIONS NC I',
    label: 'FISHPORTWHARF OPERATIONS NC I',
  },
  {
    value: 'FLUX-CORED ARC WELDING NC I',
    label: 'FLUX-CORED ARC WELDING NC I',
  },
  {
    value: 'FLUX-CORED ARC WELDING NC II',
    label: 'FLUX-CORED ARC WELDING NC II',
  },
  {
    value: 'FLUX-CORED ARC WELDING NC III',
    label: 'FLUX-CORED ARC WELDING NC III',
  },
  {
    value: 'FOOD AND BEVERAGE SERVICES NC II',
    label: 'FOOD AND BEVERAGE SERVICES NC II',
  },
  {
    value: 'FOOD AND BEVERAGE SERVICES NC III',
    label: 'FOOD AND BEVERAGE SERVICES NC III',
  },
  {
    value: 'FOOD AND BEVERAGE SERVICES NC III',
    label: 'FOOD AND BEVERAGE SERVICES NC III',
  },
  {
    value: 'FOOD AND BEVERAGE SERVICES NC IV',
    label: 'FOOD AND BEVERAGE SERVICES NC IV',
  },
  {
    value: 'FOOD AND BEVERAGE SERVICES NC IV',
    label: 'FOOD AND BEVERAGE SERVICES NC IV',
  },
  { value: 'FOOD PROCESSING NC I', label: 'FOOD PROCESSING NC I' },
  { value: 'FOOD PROCESSING NC II', label: 'FOOD PROCESSING NC II' },
  { value: 'FOOD PROCESSING NC III', label: 'FOOD PROCESSING NC III' },
  { value: 'FOOD PROCESSING NC IV', label: 'FOOD PROCESSING NC IV' },
  {
    value: 'FOOD PRODUCTION (PROFESSIONAL COOKERY) NC III',
    label: 'FOOD PRODUCTION (PROFESSIONAL COOKERY) NC III',
  },
  {
    value: 'FOOD PRODUCTION (PROFESSIONAL COOKERY) NC IV',
    label: 'FOOD PRODUCTION (PROFESSIONAL COOKERY) NC IV',
  },
  { value: 'FOOTWEAR MAKING NC II', label: 'FOOTWEAR MAKING NC II' },
  { value: 'FORGING NC II', label: 'FORGING NC II' },
  { value: 'FORGING NC III', label: 'FORGING NC III' },
  {
    value: 'FOUNDRY MELTING/CASTING NC II',
    label: 'FOUNDRY MELTING/CASTING NC II',
  },
  {
    value: 'FOUNDRY MELTING/CASTING NC III',
    label: 'FOUNDRY MELTING/CASTING NC III',
  },
  { value: 'FOUNDRY MOLDING NC II', label: 'FOUNDRY MOLDING NC II' },
  { value: 'FOUNDRY MOLDING NC III', label: 'FOUNDRY MOLDING NC III' },
  {
    value: 'FOUNDRY PATTERN MAKING NC II',
    label: 'FOUNDRY PATTERN MAKING NC II',
  },
  {
    value: 'FOUNDRY PATTERNMAKING NC III',
    label: 'FOUNDRY PATTERNMAKING NC III',
  },
  {
    value: 'FRONT OFFICE SERVICES NC II',
    label: 'FRONT OFFICE SERVICES NC II',
  },
  {
    value: 'FRONT OFFICE SERVICES NC III',
    label: 'FRONT OFFICE SERVICES NC III',
  },
  {
    value: 'FRONT OFFICE SERVICES NC IV',
    label: 'FRONT OFFICE SERVICES NC IV',
  },
  {
    value: 'FURNITURE MAKING (FINISHING) NC II',
    label: 'FURNITURE MAKING (FINISHING) NC II',
  },
  { value: 'GAME PROGRAMMING NC III', label: 'GAME PROGRAMMING NC III' },
  { value: 'GARBAGE COLLECTION NC I', label: 'GARBAGE COLLECTION NC I' },
  { value: 'GAS METAL ARC WELDING NC I', label: 'GAS METAL ARC WELDING NC I' },
  {
    value: 'GAS METAL ARC WELDING NC II',
    label: 'GAS METAL ARC WELDING NC II',
  },
  {
    value: 'GAS METAL ARC WELDING NC III',
    label: 'GAS METAL ARC WELDING NC III',
  },
  {
    value: 'GAS TUNGSTEN ARC WELDING NC II',
    label: 'GAS TUNGSTEN ARC WELDING NC II',
  },
  {
    value: 'GAS TUNGSTEN ARC WELDING NC IV',
    label: 'GAS TUNGSTEN ARC WELDING NC IV',
  },
  { value: 'GAS WELDING NC I', label: 'GAS WELDING NC I' },
  { value: 'GAS WELDING NC II', label: 'GAS WELDING NC II' },
  { value: 'GRAINS PRODUCTION NC II', label: 'GRAINS PRODUCTION NC II' },
  { value: 'HAIRDRESSING NC II', label: 'HAIRDRESSING NC II' },
  { value: 'HAIRDRESSING NC III', label: 'HAIRDRESSING NC III' },
  {
    value: 'HARD DISK DRIVE FRONT-OF-LINE OPERATION NC II',
    label: 'HARD DISK DRIVE FRONT-OF-LINE OPERATION NC II',
  },
  { value: 'HEALTH CARE SERVICES NC II', label: 'HEALTH CARE SERVICES NC II' },
  { value: 'HEAT TREATMENT', label: 'HEAT TREATMENT' },
  {
    value: 'HEAVY EQUIPMENT OPERATION (MECHANICAL) NC II',
    label: 'HEAVY EQUIPMENT OPERATION (MECHANICAL) NC II',
  },
  {
    value: 'HEO (ARTICULATED OFF-HIGHWAY DUMP TRUCK) NC II',
    label: 'HEO (ARTICULATED OFF-HIGHWAY DUMP TRUCK) NC II',
  },
  { value: 'HEO (BACKHOE LOADER) NC II', label: 'HEO (BACKHOE LOADER) NC II' },
  { value: 'HEO (BULLDOZER) NC II', label: 'HEO (BULLDOZER) NC II' },
  { value: 'HEO (CONCRETE PUMP) NC II', label: 'HEO (CONCRETE PUMP) NC II' },
  {
    value: 'HEO (CONTAINER STACKER) NC II',
    label: 'HEO (CONTAINER STACKER) NC II',
  },
  { value: 'HEO (CRAWLER CRANE) NC II', label: 'HEO (CRAWLER CRANE) NC II' },
  { value: 'HEO (CRAWLER CRANE) NC III', label: 'HEO (CRAWLER CRANE) NC III' },
  { value: 'HEO (FORKLIFT) NC II', label: 'HEO (FORKLIFT) NC II' },
  { value: 'HEO (FORKLIFT) NC II', label: 'HEO (FORKLIFT) NC II' },
  { value: 'HEO (GANTRY CRANE) NC II', label: 'HEO (GANTRY CRANE) NC II' },
  {
    value: 'HEO (HYDRAULIC EXCAVATOR) NC II',
    label: 'HEO (HYDRAULIC EXCAVATOR) NC II',
  },
  {
    value: 'HEO (HYDRAULIC EXCAVATOR) NC II',
    label: 'HEO (HYDRAULIC EXCAVATOR) NC II',
  },
  { value: 'HEO (MOTOR GRADER) NC II', label: 'HEO (MOTOR GRADER) NC II' },
  {
    value: 'HEO (OVERHEAD AND GANTRY CRANE) NC III',
    label: 'HEO (OVERHEAD AND GANTRY CRANE) NC III',
  },
  { value: 'HEO (PAVER) NC II', label: 'HEO (PAVER) NC II' },
  {
    value: 'HEO (RIGID ON-HIGHWAY DUMP TRUCK) NC II',
    label: 'HEO (RIGID ON-HIGHWAY DUMP TRUCK) NC II',
  },
  {
    value: 'HEO (RIGID ON-HIGHWAY DUMP TRUCK) NC II',
    label: 'HEO (RIGID ON-HIGHWAY DUMP TRUCK) NC II',
  },
  { value: 'HEO (ROAD ROLLER) NC II', label: 'HEO (ROAD ROLLER) NC II' },
  {
    value: 'HEO (ROUGH TERRAIN CRANE) NC II',
    label: 'HEO (ROUGH TERRAIN CRANE) NC II',
  },
  {
    value: 'HEO (ROUGH TERRAIN CRANE) NC III',
    label: 'HEO (ROUGH TERRAIN CRANE) NC III',
  },
  { value: 'HEO (SCREED) NC I', label: 'HEO (SCREED) NC I' },
  { value: 'HEO (TOWER CRANE) NC II', label: 'HEO (TOWER CRANE) NC II' },
  { value: 'HEO (TOWER CRANE) NC III', label: 'HEO (TOWER CRANE) NC III' },
  { value: 'HEO (TRANSIT MIXER) NC II', label: 'HEO (TRANSIT MIXER) NC II' },
  {
    value: 'HEO (TRUCK MOUNTED CRANE) NC II',
    label: 'HEO (TRUCK MOUNTED CRANE) NC II',
  },
  {
    value: 'HEO (TRUCK-MOUNTED CRANE) NC III',
    label: 'HEO (TRUCK-MOUNTED CRANE) NC III',
  },
  { value: 'HEO (WHEEL LOADER) NC II', label: 'HEO (WHEEL LOADER) NC II' },
  { value: 'HILOT (WELLNESS) NC II', label: 'HILOT (WELLNESS) NC II' },
  { value: 'HORTICULTURE NC III', label: 'HORTICULTURE NC III' },
  { value: 'HOUSEKEEPING NC II', label: 'HOUSEKEEPING NC II' },
  { value: 'HOUSEKEEPING NC III', label: 'HOUSEKEEPING NC III' },
  {
    value: 'HOUSEKEEPING NC III - MOBILE TRAINING PROGRAM',
    label: 'HOUSEKEEPING NC III - MOBILE TRAINING PROGRAM',
  },
  {
    value: 'ICE PLANT REFRIGERATION SERVICING NC III',
    label: 'ICE PLANT REFRIGERATION SERVICING NC III',
  },
  { value: 'ILLUSTRATION NC II', label: 'ILLUSTRATION NC II' },
  {
    value: 'INSTRUMENTATION AND CONTROL SERVICING NC II',
    label: 'INSTRUMENTATION AND CONTROL SERVICING NC II',
  },
  {
    value: 'INSTRUMENTATION AND CONTROL SERVICING NC III',
    label: 'INSTRUMENTATION AND CONTROL SERVICING NC III',
  },
  {
    value: 'INSTRUMENTATION AND CONTROL SERVICING NC IV',
    label: 'INSTRUMENTATION AND CONTROL SERVICING NC IV',
  },
  {
    value: 'JEWELRY MAKING (FINE JEWELRY) NC II',
    label: 'JEWELRY MAKING (FINE JEWELRY) NC II',
  },
  {
    value: 'JEWELRY MAKING(FINE JEWELRY) NC III',
    label: 'JEWELRY MAKING(FINE JEWELRY) NC III',
  },
  {
    value: 'LABORATORY & METROLOGY/CALIBRATION SERVICES NC II',
    label: 'LABORATORY & METROLOGY/CALIBRATION SERVICES NC II',
  },
  {
    value: 'LABORATORY & METROLOGY/CALIBRATION SERVICES NC III',
    label: 'LABORATORY & METROLOGY/CALIBRATION SERVICES NC III',
  },
  {
    value: 'LAND-BASED TRANSPORT REFRIGERATION SERVICING NC II',
    label: 'LAND-BASED TRANSPORT REFRIGERATION SERVICING NC II',
  },
  {
    value: 'LANDSCAPE INSTALLATION AND MAINTENANCE (SOFTSCAPE) NC II',
    label: 'LANDSCAPE INSTALLATION AND MAINTENANCE (SOFTSCAPE) NC II',
  },
  { value: 'LIFEGUARD SERVICES NC II', label: 'LIFEGUARD SERVICES NC II' },
  { value: 'LIFEGUARD SERVICES NC III', label: 'LIFEGUARD SERVICES NC III' },
  {
    value: 'LIGHTING FOR LIVE PERFORMANCES NC II',
    label: 'LIGHTING FOR LIVE PERFORMANCES NC II',
  },
  {
    value: 'LINE CONSTRUCTION (ELECTRIC POWER DISTRIBUTION) NC II',
    label: 'LINE CONSTRUCTION (ELECTRIC POWER DISTRIBUTION) NC II',
  },
  {
    value: 'LOCAL GUIDING SERVICES NC II',
    label: 'LOCAL GUIDING SERVICES NC II',
  },
  { value: 'MACHINING NC I', label: 'MACHINING NC I' },
  { value: 'MACHINING NC I (e-TESDA)', label: 'MACHINING NC I (e-TESDA)' },
  { value: 'MACHINING NC II', label: 'MACHINING NC II' },
  { value: 'MACHINING NC III', label: 'MACHINING NC III' },
  {
    value: 'MARINE ELECTRICITY (FINAL)3',
    label: 'MARINE ELECTRICITY (FINAL)3',
  },
  { value: 'MASONRY NC I', label: 'MASONRY NC I' },
  {
    value: 'MASONRY NC I - MOBILE TRAINING PROGRAM',
    label: 'MASONRY NC I - MOBILE TRAINING PROGRAM',
  },
  { value: 'MASONRY NC II', label: 'MASONRY NC II' },
  {
    value: 'MASONRY NC II - MOBILE TRAINING PROGRAM',
    label: 'MASONRY NC II - MOBILE TRAINING PROGRAM',
  },
  { value: 'MASONRY NC III', label: 'MASONRY NC III' },
  { value: 'MASSAGE THERAPY NC II', label: 'MASSAGE THERAPY NC II' },
  { value: 'MECHANICAL DRAFTING NC I', label: 'MECHANICAL DRAFTING NC I' },
  {
    value: 'MECHATRONICS SERVICING NC II',
    label: 'MECHATRONICS SERVICING NC II',
  },
  {
    value: 'MECHATRONICS SERVICING NC III',
    label: 'MECHATRONICS SERVICING NC III',
  },
  {
    value: 'MECHATRONICS SERVICING NC IV',
    label: 'MECHATRONICS SERVICING NC IV',
  },
  {
    value: 'MEDICAL CODING AND CLAIMS PROCESSING NC III',
    label: 'MEDICAL CODING AND CLAIMS PROCESSING NC III',
  },
  {
    value: 'MEDICAL TRANSCRIPTION NC II',
    label: 'MEDICAL TRANSCRIPTION NC II',
  },
  { value: 'METALS STAMPING NC II', label: 'METALS STAMPING NC II' },
  {
    value: 'MICROFINANCE TECHNOLOGY NC II',
    label: 'MICROFINANCE TECHNOLOGY NC II',
  },
  {
    value: 'MICROFINANCE TECHNOLOGY NC IV',
    label: 'MICROFINANCE TECHNOLOGY NC IV',
  },
  {
    value: 'MICROINSURANCE SERVICES (MUTUAL BENEFIT) NC II',
    label: 'MICROINSURANCE SERVICES (MUTUAL BENEFIT) NC II',
  },
  { value: 'MILKING OPERATION NC II', label: 'MILKING OPERATION NC II' },
  { value: 'MOLD DESIGNING NC IV', label: 'MOLD DESIGNING NC IV' },
  { value: 'MOLD MAKING NC III', label: 'MOLD MAKING NC III' },
  { value: 'MOLDMAKING NC II', label: 'MOLDMAKING NC II' },
  {
    value: 'MOTORCYCLE/SMALL ENGINE SERVICING NC II',
    label: 'MOTORCYCLE/SMALL ENGINE SERVICING NC II',
  },
  {
    value:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC II',
    label:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC II',
  },
  {
    value:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC III',
    label:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC III',
  },
  {
    value:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC IV',
    label:
      'MULTIMODAL TRANSPORT OPERATION AND LOGISTICS (SEAFREIGHT IMPORT) SERVICES NC IV',
  },
  {
    value: 'ON-HIGHWAY DUMP TRUCK (RIGID)',
    label: 'ON-HIGHWAY DUMP TRUCK (RIGID)',
  },
  {
    value: 'OPHTHALMIC LENS SERVICING NC II',
    label: 'OPHTHALMIC LENS SERVICING NC II',
  },
  {
    value: 'ORGANIC AGRICULTURE PRODUCTION NC II',
    label: 'ORGANIC AGRICULTURE PRODUCTION NC II',
  },
  {
    value: 'PAINTING MACHINE OPERATION NC II',
    label: 'PAINTING MACHINE OPERATION NC II',
  },
  {
    value: 'PERFORMING ARTS - DANCE NC II',
    label: 'PERFORMING ARTS - DANCE NC II',
  },
  {
    value: 'PERFORMING ARTS (SONG) NC II',
    label: 'PERFORMING ARTS (SONG) NC II',
  },
  {
    value: 'PERFORMING ARTS_BALLROOM DANCING NC II',
    label: 'PERFORMING ARTS_BALLROOM DANCING NC II',
  },
  {
    value: 'PEST MANAGEMENT (VEG.) NC II',
    label: 'PEST MANAGEMENT (VEG.) NC II',
  },
  { value: 'PHARMACY SERVICES NC III', label: 'PHARMACY SERVICES NC III' },
  { value: 'PHOTOGRAPHY NC II', label: 'PHOTOGRAPHY NC II' },
  {
    value: 'PIPEFITTING (METALLIC) NC II',
    label: 'PIPEFITTING (METALLIC) NC II',
  },
  { value: 'PIPEFITTING NC II', label: 'PIPEFITTING NC II' },
  { value: 'PLANT MAINTENANCE NC I', label: 'PLANT MAINTENANCE NC I' },
  {
    value: 'PLASTIC MACHINE OPERATION NC III',
    label: 'PLASTIC MACHINE OPERATION NC III',
  },
  {
    value: 'PLASTIC MACHINE OPERATION NCII',
    label: 'PLASTIC MACHINE OPERATION NCII',
  },
  { value: 'PLUMBING NC I', label: 'PLUMBING NC I' },
  { value: 'PLUMBING NC II', label: 'PLUMBING NC II' },
  { value: 'PLUMBING NC III', label: 'PLUMBING NC III' },
  {
    value: 'PRESS MACHINE OPERATION NC I',
    label: 'PRESS MACHINE OPERATION NC I',
  },
  {
    value: 'PRESSURIZED IRRIGATION SYSTEM INSTALLATION AND MAINTENANCE NC II',
    label: 'PRESSURIZED IRRIGATION SYSTEM INSTALLATION AND MAINTENANCE NC II',
  },
  { value: 'PROCESS INSPECTION NC II', label: 'PROCESS INSPECTION NC II' },
  { value: 'PROCESS INSPECTION NC III', label: 'PROCESS INSPECTION NC III' },
  {
    value: 'PROGRAMMING (.NET TECHNOLOGY) NC III',
    label: 'PROGRAMMING (.NET TECHNOLOGY) NC III',
  },
  { value: 'PROGRAMMING (JAVA) NC III', label: 'PROGRAMMING (JAVA) NC III' },
  {
    value: 'PROGRAMMING (ORACLE DATABASE) NC III',
    label: 'PROGRAMMING (ORACLE DATABASE) NC III',
  },
  {
    value: 'PUBLIC EMPLOYMENT SERVICES NC IV',
    label: 'PUBLIC EMPLOYMENT SERVICES NC IV',
  },
  { value: 'PV SYSTEM DESIGN NC III', label: 'PV SYSTEM DESIGN NC III' },
  { value: 'PV SYSTEM SERVICING NC III', label: 'PV SYSTEM SERVICING NC III' },
  {
    value: 'PV SYSTEMS INSTALLATION NC II',
    label: 'PV SYSTEMS INSTALLATION NC II',
  },
  { value: 'PYROTECHNICS NC II', label: 'PYROTECHNICS NC II' },
  {
    value: 'RAC SERVICING (DOMRAC) NC II - NEW',
    label: 'RAC SERVICING (DOMRAC) NC II - NEW',
  },
  {
    value: 'RAC SERVICING (PACU-CRE) NC III',
    label: 'RAC SERVICING (PACU-CRE) NC III',
  },
  {
    value: 'RATING FORMING PART OF A NAVIGATIONAL WATCH NC II (II-4)',
    label: 'RATING FORMING PART OF A NAVIGATIONAL WATCH NC II (II-4)',
  },
  {
    value: 'RATING FORMING PART OF AN ENGINEERING WATCH NC II (III-4)',
    label: 'RATING FORMING PART OF AN ENGINEERING WATCH NC II (III-4)',
  },
  { value: 'REAL ESTATE SERVICES NC II', label: 'REAL ESTATE SERVICES NC II' },
  {
    value: 'REINFORCING STEEL WORKS NC II',
    label: 'REINFORCING STEEL WORKS NC II',
  },
  {
    value: 'RICE MACHINERY OPERATIONS NC II',
    label: 'RICE MACHINERY OPERATIONS NC II',
  },
  { value: 'RIGGING NC I', label: 'RIGGING NC I' },
  { value: 'RUBBER PROCESSING NC II', label: 'RUBBER PROCESSING NC II' },
  { value: 'RUBBER PRODUCTION NC II', label: 'RUBBER PRODUCTION NC II' },
  {
    value: 'SANITARY LANDFILL OPERATIONS NC II',
    label: 'SANITARY LANDFILL OPERATIONS NC II',
  },
  {
    value: 'SANITARY LANDFILL OPERATIONS NC III',
    label: 'SANITARY LANDFILL OPERATIONS NC III',
  },
  { value: 'SCAFFOLD ERECTION NC II', label: 'SCAFFOLD ERECTION NC II' },
  {
    value: 'SCAFFOLDING WORKS NC II (SUPPORTED TYPE SCAFFOLD)',
    label: 'SCAFFOLDING WORKS NC II (SUPPORTED TYPE SCAFFOLD)',
  },
  { value: 'SEAWEED PRODUCTION NC II', label: 'SEAWEED PRODUCTION NC II' },
  { value: 'SECURITY SERVICES NC I', label: 'SECURITY SERVICES NC I' },
  { value: 'SECURITY SERVICES NC II', label: 'SECURITY SERVICES NC II' },
  {
    value: 'SEMICONDUCTOR BACK-END OPERATION NC II',
    label: 'SEMICONDUCTOR BACK-END OPERATION NC II',
  },
  {
    value: 'SEMICONDUCTOR FRONT-OF-LINE OPERATION NC II',
    label: 'SEMICONDUCTOR FRONT-OF-LINE OPERATION NC II',
  },
  {
    value: 'SHIPS CATERING SERVICES NC I',
    label: 'SHIPS CATERING SERVICES NC I',
  },
  {
    value: "SHIPS' CATERING SERVICES NC III (SHIPS' COOKS)",
    label: "SHIPS' CATERING SERVICES NC III (SHIPS' COOKS)",
  },
  {
    value: 'SLAUGHTERING OPERATIONS (LARGE ANIMALS) NC II',
    label: 'SLAUGHTERING OPERATIONS (LARGE ANIMALS) NC II',
  },
  {
    value: 'SLAUGHTERING OPERATIONS (SWINE) NC II',
    label: 'SLAUGHTERING OPERATIONS (SWINE) NC II',
  },
  { value: 'SMAW NC I', label: 'SMAW NC I' },
  { value: 'SMAW NC II', label: 'SMAW NC II' },
  { value: 'SMAW NC III', label: 'SMAW NC III' },
  { value: 'SMAW NC IV', label: 'SMAW NC IV' },
  { value: 'STRUCTURAL ERECTION NC II', label: 'STRUCTURAL ERECTION NC II' },
  { value: 'SUBMERGED ARC WELDING NC I', label: 'SUBMERGED ARC WELDING NC I' },
  {
    value: 'SUBMERGED ARC WELDING NC II',
    label: 'SUBMERGED ARC WELDING NC II',
  },
  { value: 'SUGARCANE PRODUCTION NC II', label: 'SUGARCANE PRODUCTION NC II' },
  {
    value: 'SYSTEM FORMWORK INSTALLATION NC II',
    label: 'SYSTEM FORMWORK INSTALLATION NC II',
  },
  { value: 'TAILORING (CASUAL) NC II', label: 'TAILORING (CASUAL) NC II' },
  { value: 'TECHNICAL DRAFTING NC II', label: 'TECHNICAL DRAFTING NC II' },
  {
    value:
      'TELECOM OSP AND SUBSCRIBER LINE INSTALLATION (COPPER CABLE-POTS AND DSL) NC II - NEW',
    label:
      'TELECOM OSP AND SUBSCRIBER LINE INSTALLATION (COPPER CABLE-POTS AND DSL) NC II - NEW',
  },
  {
    value: 'TELECOM OSP INSTALLATION (FIBER OPTIC CABLE) NC II - NEW',
    label: 'TELECOM OSP INSTALLATION (FIBER OPTIC CABLE) NC II - NEW',
  },
  { value: 'TILE SETTING NC II', label: 'TILE SETTING NC II' },
  {
    value: 'TILE SETTING NC II - MOBILE TRAINING PROGRAM',
    label: 'TILE SETTING NC II - MOBILE TRAINING PROGRAM',
  },
  {
    value: 'TINSMITHING (AUTOMOTIVE MANUFACTURING) NC II',
    label: 'TINSMITHING (AUTOMOTIVE MANUFACTURING) NC II',
  },
  { value: 'TOOL AND DIE MAKING NC II', label: 'TOOL AND DIE MAKING NC II' },
  {
    value: 'TOUR PACKAGING (FIT AD HOC DOMESTIC) SERVICES NC II',
    label: 'TOUR PACKAGING (FIT AD HOC DOMESTIC) SERVICES NC II',
  },
  {
    value: 'TOURISM PROMOTION SERVICES NC II',
    label: 'TOURISM PROMOTION SERVICES NC II',
  },
  {
    value: 'TR TRANSMISSION LINE INSTALLATION & MAINTENANCE NC III',
    label: 'TR TRANSMISSION LINE INSTALLATION & MAINTENANCE NC III',
  },
  {
    value: 'TR TRANSMISSION LINE INSTALLATION AND MAINTENANCE NC II',
    label: 'TR TRANSMISSION LINE INSTALLATION AND MAINTENANCE NC II',
  },
  {
    value: 'TRAINERS METHODOLOGY LEVEL I',
    label: 'TRAINERS METHODOLOGY LEVEL I',
  },
  {
    value: 'TRAINERS METHODOLOGY LEVEL I (IN-COMPANY TRAINER)',
    label: 'TRAINERS METHODOLOGY LEVEL I (IN-COMPANY TRAINER)',
  },
  {
    value: 'TRAINERS METHODOLOGY LEVEL II',
    label: 'TRAINERS METHODOLOGY LEVEL II',
  },
  {
    value: 'TRANSMISSION LINE INSTALLATION & MAINTENANCE NC II',
    label: 'TRANSMISSION LINE INSTALLATION & MAINTENANCE NC II',
  },
  {
    value: 'TRANSMISSION LINE INSTALLATION & MAINTENANCE NC III',
    label: 'TRANSMISSION LINE INSTALLATION & MAINTENANCE NC III',
  },
  {
    value: 'TRANSMISSION LINE INSTALLATION AND MAINTENANCE NC IV',
    label: 'TRANSMISSION LINE INSTALLATION AND MAINTENANCE NC IV',
  },
  {
    value: 'TRANSPORT RAC SERVICING NC II',
    label: 'TRANSPORT RAC SERVICING NC II',
  },
  { value: 'TRAVEL SERVICES NC II', label: 'TRAVEL SERVICES NC II' },
  {
    value: 'VISUAL GRAPHIC DESIGN NC III - PRINT MEDIA',
    label: 'VISUAL GRAPHIC DESIGN NC III - PRINT MEDIA',
  },
  {
    value: 'VISUAL GRAPHIC DESIGN NC III - ELECTRONIC MEDIA',
    label: 'VISUAL GRAPHIC DESIGN NC III - ELECTRONIC MEDIA',
  },
  { value: 'WAREHOUSING SERVICES NC II', label: 'WAREHOUSING SERVICES NC II' },
  {
    value: 'WAREHOUSING SERVICES NC III',
    label: 'WAREHOUSING SERVICES NC III',
  },
  { value: 'WAREHOUSING SERVICES NC IV', label: 'WAREHOUSING SERVICES NC IV' },
  { value: 'WEB DEVELOPMENT NC III', label: 'WEB DEVELOPMENT NC III' },
  { value: 'ANIMATION NC III', label: 'ANIMATION NC III' },
];

export default tesdaSkillsCertsTypes
