export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CAPTCHA_AUTH_SUCCESS = 'CAPTCHA_AUTH_SUCCESS';
export const CAPTCHA_AUTH_FAIL = 'CAPTCHA_AUTH_FAIL';
export const CAPTCHA_AUTH_EXPIRED = 'CAPTCHA_AUTH_EXPIRED';
export const CAPTCHA_AUTH_RESET = 'CAPTCHA_AUTH_RESET';

export const AUTH_GET_STORAGE = 'AUTH_GET_STORAGE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const TOGGLE_DASHBOARD_SIDEBAR = 'TOGGLE_DASHBOARD_SIDEBAR';
export const TOGGLE_DASHBOARD_ASIDE = 'TOGGLE_DASHBOARD_ASIDE';
export const TOGGLE_DASHBOARD_DARKMODE = 'TOGGLE_DASHBOARD_DARKMODE';
