const barangayOptionTypes =[
  { value: 'Adcadarao', label: 'Adcadarao' },
  { value: 'Agbobolo', label: 'Agbobolo' },
  { value: 'Badiangan', label: 'Badiangan' },
  { value: 'Bato Biasong', label: 'Bato Biasong' },
  { value: 'Bay-ang', label: 'Bay-ang' },
  { value: 'Bucana Bunglas', label: 'Bucana Bunglas' },
  { value: 'Central', label: 'Central' },
  { value: 'Culasi', label: 'Culasi' },
  { value: 'Lanjagan', label: 'Lanjagan' },
  { value: 'Luca', label: 'Luca' },
  { value: 'Malayu-an', label: 'Malayu-an' },
  { value: 'Abang-abang', label: 'Abang-abang' },
  { value: 'Agsing', label: 'Agsing' },
  { value: 'Atabay', label: 'Atabay' },
  { value: 'Bagsakan', label: 'Bagsakan' },
  { value: 'Baguingin-Lanot', label: 'Baguingin-Lanot' },
  { value: 'Bagumbayan-Ilajas', label: 'Bagumbayan-Ilajas' },
  { value: 'Balabago', label: 'Balabago' },
  { value: 'Ban-ag', label: 'Ban-ag' },
  { value: 'Bancal', label: 'Bancal' },
  { value: 'Agbatuan', label: 'Agbatuan' },
  { value: 'Badiang', label: 'Badiang' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Balunos', label: 'Balunos' },
  { value: 'Cag-an', label: 'Cag-an' },
  { value: 'Camiros', label: 'Camiros' },
  { value: 'Dangula-an', label: 'Dangula-an' },
  { value: 'Guipis', label: 'Guipis' },
  { value: 'Manganese', label: 'Manganese' },
  { value: 'Medina', label: 'Medina' },
  { value: 'Agusipan', label: 'Agusipan' },
  { value: 'Astorga', label: 'Astorga' },
  { value: 'Bingauan', label: 'Bingauan' },
  { value: 'Bita-oyan', label: 'Bita-oyan' },
  { value: 'Botong', label: 'Botong' },
  { value: 'Budiawe', label: 'Budiawe' },
  { value: 'Cabanga-an', label: 'Cabanga-an' },
  { value: 'Cabayogan', label: 'Cabayogan' },
  { value: 'Calansanan', label: 'Calansanan' },
  { value: 'Catubig', label: 'Catubig' },
  { value: 'Aranjuez', label: 'Aranjuez' },
  { value: 'Bacolod', label: 'Bacolod' },
  { value: 'Balanti-an', label: 'Balanti-an' },
  { value: 'Batuan', label: 'Batuan' },
  { value: 'Cabalic', label: 'Cabalic' },
  { value: 'Camambugan', label: 'Camambugan' },
  { value: 'Dolores', label: 'Dolores' },
  { value: 'Gimamanay', label: 'Gimamanay' },
  { value: 'Alacaygan', label: 'Alacaygan' },
  { value: 'Bariga', label: 'Bariga' },
  { value: 'Belen', label: 'Belen' },
  { value: 'Bobon', label: 'Bobon' },
  { value: 'Bularan', label: 'Bularan' },
  { value: 'Carmelo', label: 'Carmelo' },
  { value: 'De La Paz', label: 'De La Paz' },
  { value: 'Dugwakan', label: 'Dugwakan' },
  { value: 'Fuentes', label: 'Fuentes' },
  { value: 'Acuit', label: 'Acuit' },
  { value: 'Agcuyawan Calsada', label: 'Agcuyawan Calsada' },
  { value: 'Agcuyawan Pulo', label: 'Agcuyawan Pulo' },
  { value: 'Bagongbong', label: 'Bagongbong' },
  { value: 'Baras', label: 'Baras' },
  { value: 'Bungca', label: 'Bungca' },
  { value: 'Cabilauan', label: 'Cabilauan' },
  { value: 'Cruz', label: 'Cruz' },
  { value: 'Guintas', label: 'Guintas' },
  { value: 'Igbong', label: 'Igbong' },
  { value: 'Ilaud Poblacion', label: 'Ilaud Poblacion' },
  { value: 'Ilaya Poblacion', label: 'Ilaya Poblacion' },
  { value: 'Jalaud', label: 'Jalaud' },
  { value: 'Bugnay', label: 'Bugnay' },
  { value: 'California', label: 'California' },
  { value: 'De la Peña', label: 'De la Peña' },
  { value: 'Del Pilar', label: 'Del Pilar' },
  { value: 'General Luna', label: 'General Luna' },
  { value: 'La Fortuna', label: 'La Fortuna' },
  { value: 'Lipata', label: 'Lipata' },
  { value: 'Natividad', label: 'Natividad' },
  { value: 'Nueva Invencion', label: 'Nueva Invencion' },
  { value: 'Nueva Sevilla', label: 'Nueva Sevilla' },
  { value: 'Alapasco', label: 'Alapasco' },
  { value: 'Alinsolong', label: 'Alinsolong' },
  { value: 'Banban', label: 'Banban' },
  { value: 'Batad Viejo', label: 'Batad Viejo' },
  { value: 'Binon-an', label: 'Binon-an' },
  { value: 'Bolhog', label: 'Bolhog' },
  { value: 'Bulak Norte', label: 'Bulak Norte' },
  { value: 'Bulak Sur', label: 'Bulak Sur' },
  { value: 'Cabagohan', label: 'Cabagohan' },
  { value: 'Calangag', label: 'Calangag' },
  { value: 'Caw-i', label: 'Caw-i' },
  { value: 'Drancalan', label: 'Drancalan' },
  { value: 'Embarcadero', label: 'Embarcadero' },
  { value: 'Agba-o', label: 'Agba-o' },
  { value: 'Balud I', label: 'Balud I' },
  { value: 'Alabidhan', label: 'Alabidhan' },
  { value: 'Bulabog', label: 'Bulabog' },
  { value: 'Balud II', label: 'Balud II' },
  { value: 'Balud Lilo-an', label: 'Balud Lilo-an' },
  { value: 'Dawis Centro', label: 'Dawis Centro' },
  { value: 'Dawis Norte', label: 'Dawis Norte' },
  { value: 'Dawis Sur', label: 'Dawis Sur' },
  { value: 'Gines', label: 'Gines' },
  { value: 'Ilawod Poblacion', label: 'Ilawod Poblacion' },
  { value: 'Ilaya Poblacion', label: 'Ilaya Poblacion' },
  { value: 'Inagdangan Centro', label: 'Inagdangan Centro' },
  { value: 'Inagdangan Norte', label: 'Inagdangan Norte' },
  { value: 'Inagdangan Sur', label: 'Inagdangan Sur' },
  { value: 'Jalaud Norte', label: 'Jalaud Norte' },
  { value: 'Jalaud Sur', label: 'Jalaud Sur' },
  { value: 'Libongcogon', label: 'Libongcogon' },
  { value: 'Malunang', label: 'Malunang' },
  { value: 'Pajo', label: 'Pajo' },
  { value: 'Sambag', label: 'Sambag' },
  { value: 'Sigangao', label: 'Sigangao' },
  { value: 'Talauguis', label: 'Talauguis' },
  { value: 'Talibong', label: 'Talibong' },
  { value: 'Tubigan', label: 'Tubigan' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Tuburan Sulbod', label: 'Tuburan Sulbod' },
  { value: 'Adgao', label: 'Adgao' },
  { value: 'Cairohan', label: 'Cairohan' },
  { value: 'Ago', label: 'Ago' },
  { value: 'Guinhulacan', label: 'Guinhulacan' },
  { value: 'Inamyungan', label: 'Inamyungan' },
  { value: 'Malitbog Ilawod', label: 'Malitbog Ilawod' },
  { value: 'Ambarihon', label: 'Ambarihon' },
  { value: 'Malitbog Ilaya', label: 'Malitbog Ilaya' },
  { value: 'Ayubo', label: 'Ayubo' },
  { value: 'Ngingi-an', label: 'Ngingi-an' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Bacan', label: 'Bacan' },
  { value: 'Quinangyana', label: 'Quinangyana' },
  { value: 'Quinar-Upan', label: 'Quinar-Upan' },
  { value: 'Badiang', label: 'Badiang' },
  { value: 'Tapacon', label: 'Tapacon' },
  { value: 'Tubod', label: 'Tubod' },
  { value: 'Bagunanay', label: 'Bagunanay' },
  { value: 'Acao', label: 'Acao' },
  { value: 'Balicua', label: 'Balicua' },
  { value: 'Amerang', label: 'Amerang' },
  { value: 'Bantayanan', label: 'Bantayanan' },
  { value: 'Amurao', label: 'Amurao' },
  { value: 'Anuang', label: 'Anuang' },
  { value: 'Batga', label: 'Batga' },
  { value: 'Ayaman', label: 'Ayaman' },
  { value: 'Ayong', label: 'Ayong' },
  { value: 'Bacan', label: 'Bacan' },
  { value: 'Bato', label: 'Bato' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Baluyan', label: 'Baluyan' },
  { value: 'Bikil', label: 'Bikil' },
  { value: 'Banguit', label: 'Banguit' },
  { value: 'Bulay', label: 'Bulay' },
  { value: 'Boloc', label: 'Boloc' },
  { value: 'Cadoldolan', label: 'Cadoldolan' },
  { value: 'Cagban', label: 'Cagban' },
  { value: 'Bondoc', label: 'Bondoc' },
  { value: 'Calawagan', label: 'Calawagan' },
  { value: 'Calayo', label: 'Calayo' },
  { value: 'Duyanduyan', label: 'Duyanduyan' },
  { value: 'Borong', label: 'Borong' },
  { value: 'Agcalaga', label: 'Agcalaga' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Aglibacao', label: 'Aglibacao' },
  { value: 'Cadabdab', label: 'Cadabdab' },
  { value: 'Aglonok', label: 'Aglonok' },
  { value: 'Alibunan', label: 'Alibunan' },
  { value: 'Daga-ay', label: 'Daga-ay' },
  { value: 'Badlan Grande', label: 'Badlan Grande' },
  { value: 'Badlan Pequeño', label: 'Badlan Pequeño' },
  { value: 'Desposorio', label: 'Desposorio' },
  { value: 'Igdampog Norte', label: 'Igdampog Norte' },
  { value: 'Badu', label: 'Badu' },
  { value: 'Igdampog Sur', label: 'Igdampog Sur' },
  { value: 'Baje San Julian', label: 'Baje San Julian' },
  { value: 'Balaticon', label: 'Balaticon' },
  { value: 'Igpaho', label: 'Igpaho' },
  { value: 'Banban Grande', label: 'Banban Grande' },
  { value: 'Igtuble', label: 'Igtuble' },
  { value: 'Ingay', label: 'Ingay' },
  { value: 'Isauan', label: 'Isauan' },
  { value: 'Banban Pequeño', label: 'Banban Pequeño' },
  { value: 'Jolason', label: 'Jolason' },
  { value: 'Jona', label: 'Jona' },
  { value: 'Alipata', label: 'Alipata' },
  { value: 'La-ag', label: 'La-ag' },
  { value: 'Lanag Norte', label: 'Lanag Norte' },
  { value: 'Lanag Sur', label: 'Lanag Sur' },
  { value: 'Male', label: 'Male' },
  { value: 'Abong', label: 'Abong' },
  { value: 'Alipata', label: 'Alipata' },
  { value: 'Mayang', label: 'Mayang' },
  { value: 'Asluman', label: 'Asluman' },
  { value: 'Bancal', label: 'Bancal' },
  { value: 'Molina', label: 'Molina' },
  { value: 'Barangcalan', label: 'Barangcalan' },
  { value: 'Barosbos', label: 'Barosbos' },
  { value: 'Morcillas', label: 'Morcillas' },
  { value: 'Binuluangan', label: 'Binuluangan' },
  { value: 'Nagba', label: 'Nagba' },
  { value: 'Bito-on', label: 'Bito-on' },
  { value: 'Bolo', label: 'Bolo' },
  { value: 'Navillan', label: 'Navillan' },
  { value: 'Buaya', label: 'Buaya' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Pinamacalan', label: 'Pinamacalan' },
  { value: 'Cabilao Grande', label: 'Cabilao Grande' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'Aglosong', label: 'Aglosong' },
  { value: 'Sibucauan', label: 'Sibucauan' },
  { value: 'Agnaga', label: 'Agnaga' },
  { value: 'Bacjawan Norte', label: 'Bacjawan Norte' },
  { value: 'Singon', label: 'Singon' },
  { value: 'Bacjawan Sur', label: 'Bacjawan Sur' },
  { value: 'Bagongon', label: 'Bagongon' },
  { value: 'Tabat', label: 'Tabat' },
  { value: 'Batiti', label: 'Batiti' },
  { value: 'Tagpu-an', label: 'Tagpu-an' },
  { value: 'Talento', label: 'Talento' },
  { value: 'Teniente Benito', label: 'Teniente Benito' },
  { value: 'Victoria', label: 'Victoria' },
  { value: 'Zone I (Poblacion)', label: 'Zone I (Poblacion)' },
  { value: 'Zone II (Poblacion)', label: 'Zone II (Poblacion)' },
  { value: 'Zone III (Poblacion)', label: 'Zone III (Poblacion)' },
  { value: 'Alupidian', label: 'Alupidian' },
  { value: 'Atabayan', label: 'Atabayan' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Baguingin', label: 'Baguingin' },
  { value: 'Bagumbayan', label: 'Bagumbayan' },
  { value: 'Bangkal', label: 'Bangkal' },
  { value: 'Bantud', label: 'Bantud' },
  { value: 'Barangay 1 (Poblacion)', label: 'Barangay 1 (Poblacion)' },
  { value: 'Botlog', label: 'Botlog' },
  { value: 'Barangay 2 (Poblacion)', label: 'Barangay 2 (Poblacion)' },
  { value: 'Calamigan', label: 'Calamigan' },
  { value: 'Barangay 3 (Poblacion)', label: 'Barangay 3 (Poblacion)' },
  { value: 'Dungon', label: 'Dungon' },
  { value: 'Barangay 4 (Poblacion)', label: 'Barangay 4 (Poblacion)' },
  { value: 'Barangay 5 (Poblacion)', label: 'Barangay 5 (Poblacion)' },
  { value: 'Barangay 6 (Poblacion)', label: 'Barangay 6 (Poblacion)' },
  { value: 'Barangay 7 (Poblacion)', label: 'Barangay 7 (Poblacion)' },
  { value: 'Barangay 8 (Poblacion)', label: 'Barangay 8 (Poblacion)' },
  { value: 'Barangay 9 (Poblacion)', label: 'Barangay 9 (Poblacion)' },
  { value: 'Barosong', label: 'Barosong' },
  { value: 'Barroc', label: 'Barroc' },
  { value: 'Bayuco', label: 'Bayuco' },
  { value: 'Binaliuan Mayor', label: 'Binaliuan Mayor' },
  { value: 'Binaliuan Menor', label: 'Binaliuan Menor' },
  { value: 'Bitas', label: 'Bitas' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Bugasongan', label: 'Bugasongan' },
  { value: 'Buyu-an', label: 'Buyu-an' },
  { value: 'Canabuan', label: 'Canabuan' },
  { value: 'Cansilayan', label: 'Cansilayan' },
  { value: 'Cordova Norte', label: 'Cordova Norte' },
  { value: 'Cordova Sur', label: 'Cordova Sur' },
  { value: 'Danao', label: 'Danao' },
  { value: 'Dapdap', label: 'Dapdap' },
  { value: 'Dorong-an', label: 'Dorong-an' },
  { value: 'Guisian', label: 'Guisian' },
  { value: 'Isauan', label: 'Isauan' },
  { value: 'Isian', label: 'Isian' },
  { value: 'Jamog', label: 'Jamog' },
  { value: 'Lanag', label: 'Lanag' },
  { value: 'Linobayan', label: 'Linobayan' },
  { value: 'Lubog', label: 'Lubog' },
  { value: 'Nagba', label: 'Nagba' },
  { value: 'Namocon', label: 'Namocon' },
  { value: 'Napnapan Norte', label: 'Napnapan Norte' },
  { value: 'Napnapan Sur', label: 'Napnapan Sur' },
  { value: 'Olo Barroc', label: 'Olo Barroc' },
  { value: 'Parara Norte', label: 'Parara Norte' },
  { value: 'Parara Sur', label: 'Parara Sur' },
  { value: 'San Rafael', label: 'San Rafael' },
  { value: 'Sermon', label: 'Sermon' },
  { value: 'Sipitan', label: 'Sipitan' },
  { value: 'Supa', label: 'Supa' },
  { value: 'Tan Pael', label: 'Tan Pael' },
  { value: 'Taro', label: 'Taro' },
  { value: 'Igbon', label: 'Igbon' },
  { value: 'Jamul-Awon', label: 'Jamul-Awon' },
  { value: 'Abangay', label: 'Abangay' },
  { value: 'Agsalanan', label: 'Agsalanan' },
  { value: 'Agtatacay', label: 'Agtatacay' },
  { value: 'Alegria', label: 'Alegria' },
  { value: 'Bongloy', label: 'Bongloy' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Caguyuman', label: 'Caguyuman' },
  { value: 'Calicuang', label: 'Calicuang' },
  { value: 'Camambugan', label: 'Camambugan' },
  { value: 'Dawis', label: 'Dawis' },
  { value: 'Aguirre', label: 'Aguirre' },
  { value: 'Aldeguer', label: 'Aldeguer' },
  { value: 'Alibayog', label: 'Alibayog' },
  { value: 'Anoring', label: 'Anoring' },
  { value: 'Apelo', label: 'Apelo' },
  { value: 'Apologista', label: 'Apologista' },
  { value: 'Aposaga', label: 'Aposaga' },
  { value: 'Arante', label: 'Arante' },
  { value: 'Ardemil', label: 'Ardemil' },
  { value: 'Aspera', label: 'Aspera' },
  { value: 'Aswe-Pabriaga', label: 'Aswe-Pabriaga' },
  { value: 'Bagaygay', label: 'Bagaygay' },
  { value: 'Bakabak', label: 'Bakabak' },
  { value: 'Batitao', label: 'Batitao' },
  { value: 'Bato', label: 'Bato' },
  { value: 'Castor', label: 'Castor' },
  { value: 'Crespo', label: 'Crespo' },
  { value: 'Del Castillo', label: 'Del Castillo' },
  { value: 'Devera', label: 'Devera' },
  { value: 'Domingo', label: 'Domingo' },
  { value: 'Ferraris', label: 'Ferraris' },
  { value: 'Gildore', label: 'Gildore' },
  { value: 'Improgo', label: 'Improgo' },
  { value: 'Juaneza', label: 'Juaneza' },
  { value: 'Labigan', label: 'Labigan' },
  { value: 'Lanciola', label: 'Lanciola' },
  { value: 'Latawan', label: 'Latawan' },
  { value: 'Malapaya', label: 'Malapaya' },
  { value: 'Muyco', label: 'Muyco' },
  { value: 'Padios', label: 'Padios' },
  { value: 'Pasig', label: 'Pasig' },
  { value: 'Poblacion Ilawod', label: 'Poblacion Ilawod' },
  { value: 'Poblacion Ilaya', label: 'Poblacion Ilaya' },
  { value: 'Poblacion Market', label: 'Poblacion Market' },
  { value: 'Posadas', label: 'Posadas' },
  { value: 'Preciosa', label: 'Preciosa' },
  { value: 'Salcedo', label: 'Salcedo' },
  { value: 'San Luis', label: 'San Luis' },
  { value: 'Tady', label: 'Tady' },
  { value: 'Tentay', label: 'Tentay' },
  { value: 'Villahermosa', label: 'Villahermosa' },
  { value: 'Zerrudo', label: 'Zerrudo' },
  { value: 'Agusipan', label: 'Agusipan' },
  { value: 'Agutayan', label: 'Agutayan' },
  { value: 'Bagumbayan', label: 'Bagumbayan' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Balibagan Este', label: 'Balibagan Este' },
  { value: 'Balibagan Oeste', label: 'Balibagan Oeste' },
  { value: 'Ban-ag', label: 'Ban-ag' },
  { value: 'Bantay', label: 'Bantay' },
  {
    value: 'Barangay Zone I (Poblacion)',
    label: 'Barangay Zone I (Poblacion)',
  },
  {
    value: 'Barangay Zone II (Poblacion)',
    label: 'Barangay Zone II (Poblacion)',
  },
  {
    value: 'Barangay Zone III (Poblacion)',
    label: 'Barangay Zone III (Poblacion)',
  },
  {
    value: 'Barangay Zone IV (Poblacion)',
    label: 'Barangay Zone IV (Poblacion)',
  },
  {
    value: 'Barangay Zone V (Poblacion)',
    label: 'Barangay Zone V (Poblacion)',
  },
  {
    value: 'Barangay Zone VI (Poblacion)',
    label: 'Barangay Zone VI (Poblacion)',
  },
  { value: 'Barasan Este', label: 'Barasan Este' },
  { value: 'Barasan Oeste', label: 'Barasan Oeste' },
  { value: 'Binangkilan', label: 'Binangkilan' },
  { value: 'Bitaog-Taytay', label: 'Bitaog-Taytay' },
  { value: 'Bolong Este', label: 'Bolong Este' },
  { value: 'Bolong Oeste', label: 'Bolong Oeste' },
  { value: 'Buayahon', label: 'Buayahon' },
  { value: 'Buyo', label: 'Buyo' },
  { value: 'Cabugao Norte', label: 'Cabugao Norte' },
  { value: 'Cabugao Sur', label: 'Cabugao Sur' },
  { value: 'Cadagmayan Norte', label: 'Cadagmayan Norte' },
  { value: 'Cadagmayan Sur', label: 'Cadagmayan Sur' },
  { value: 'Cafe', label: 'Cafe' },
  { value: 'Calaboa Este', label: 'Calaboa Este' },
  { value: 'Calaboa Oeste', label: 'Calaboa Oeste' },
  { value: 'Camambugan', label: 'Camambugan' },
  { value: 'Canipayan', label: 'Canipayan' },
  { value: 'Conaynay', label: 'Conaynay' },
  { value: 'Daga', label: 'Daga' },
  { value: 'Dalid', label: 'Dalid' },
  { value: 'Duyanduyan', label: 'Duyanduyan' },
  { value: 'Gen. Martin T. Delgado', label: 'Gen. Martin T. Delgado' },
  { value: 'Guno', label: 'Guno' },
  { value: 'Inangayan', label: 'Inangayan' },
  { value: 'Jibao-an', label: 'Jibao-an' },
  { value: 'Lacadon', label: 'Lacadon' },
  { value: 'Lanag', label: 'Lanag' },
  { value: 'Lupa', label: 'Lupa' },
  { value: 'Magancina', label: 'Magancina' },
  { value: 'Malawog', label: 'Malawog' },
  { value: 'Mambuyo', label: 'Mambuyo' },
  { value: 'Manhayang', label: 'Manhayang' },
  { value: 'Miraga-Guibuangan', label: 'Miraga-Guibuangan' },
  { value: 'Nasugban', label: 'Nasugban' },
  { value: 'Omambog', label: 'Omambog' },
  { value: 'Pal-Agon', label: 'Pal-Agon' },
  { value: 'Pungsod', label: 'Pungsod' },
  { value: 'San Sebastian', label: 'San Sebastian' },
  { value: 'Sangcate', label: 'Sangcate' },
  { value: 'Tagsing', label: 'Tagsing' },
  { value: 'Talanghauan', label: 'Talanghauan' },
  { value: 'Talongadian', label: 'Talongadian' },
  { value: 'Tigtig', label: 'Tigtig' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Tugas', label: 'Tugas' },
  { value: 'Tungay', label: 'Tungay' },
  { value: 'Aripdip', label: 'Aripdip' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Calaigang', label: 'Calaigang' },
  { value: 'Ilongbukid', label: 'Ilongbukid' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Poscolon', label: 'Poscolon' },
  { value: 'San Andres', label: 'San Andres' },
  { value: 'San Dionisio', label: 'San Dionisio' },
  { value: 'San Florentino', label: 'San Florentino' },
  {
    value: 'Barangay 1 Poblacion (Roxas St.)',
    label: 'Barangay 1 Poblacion (Roxas St.)',
  },
  {
    value: 'Barangay 10 (Poblacion R. V. Sanchez St. South)',
    label: 'Barangay 10 (Poblacion R. V. Sanchez St. South)',
  },
  {
    value: 'Barangay 11 Poblacion (R. V. Sanchez St. North)',
    label: 'Barangay 11 Poblacion (R. V. Sanchez St. North)',
  },
  {
    value: 'Barangay 12 Poblacion (Sales Malaga Saliedo)',
    label: 'Barangay 12 Poblacion (Sales Malaga Saliedo)',
  },
  {
    value: 'Barangay 13 Poblacion (Santa Rita-Saclauso St.)',
    label: 'Barangay 13 Poblacion (Santa Rita-Saclauso St.)',
  },
  {
    value: 'Barangay 14 Poblacion (San Miguel North)',
    label: 'Barangay 14 Poblacion (San Miguel North)',
  },
  {
    value: 'Barangay 15 Poblacion (San Miguel South)',
    label: 'Barangay 15 Poblacion (San Miguel South)',
  },
  {
    value: 'Barangay 16 Poblacion (San Agustin St.)',
    label: 'Barangay 16 Poblacion (San Agustin St.)',
  },
  {
    value: 'Barangay 2 Poblacion (Savilla Santo Rosario)',
    label: 'Barangay 2 Poblacion (Savilla Santo Rosario)',
  },
  {
    value: 'Barangay 3 Poblacion (A. S. Suarez St. Zone 1)',
    label: 'Barangay 3 Poblacion (A. S. Suarez St. Zone 1)',
  },
  {
    value: 'Barangay 4 Poblacion (A. S. Suarez East)',
    label: 'Barangay 4 Poblacion (A. S. Suarez East)',
  },
  {
    value: 'Barangay 5 Poblacion (Santiago St. North)',
    label: 'Barangay 5 Poblacion (Santiago St. North)',
  },
  {
    value: 'Barangay 6 Poblacion (Santiago St. South)',
    label: 'Barangay 6 Poblacion (Santiago St. South)',
  },
  {
    value: 'Barangay 7 Poblacion (San Roque St. South)',
    label: 'Barangay 7 Poblacion (San Roque St. South)',
  },
  {
    value: 'Barangay 8 Poblacion (Montano-San Roque)',
    label: 'Barangay 8 Poblacion (Montano-San Roque)',
  },
  {
    value: 'Barangay 9 Poblacion (Salazar San Jose)',
    label: 'Barangay 9 Poblacion (Salazar San Jose)',
  },
  { value: 'Consolacion', label: 'Consolacion' },
  { value: 'Igtambo', label: 'Igtambo' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'Santa Cruz', label: 'Santa Cruz' },
  { value: 'Santa Teresa', label: 'Santa Teresa' },
  { value: 'Santo Angel', label: 'Santo Angel' },
  { value: 'Santo Niño', label: 'Santo Niño' },
  { value: 'Maraguit', label: 'Maraguit' },
  { value: 'Magsaysay', label: 'Magsaysay' },
  { value: 'Agboy Norte', label: 'Agboy Norte' },
  { value: 'Agboy Sur', label: 'Agboy Sur' },
  { value: 'Agta', label: 'Agta' },
  { value: 'Ambulong', label: 'Ambulong' },
  { value: 'Anonang', label: 'Anonang' },
  { value: 'Apian', label: 'Apian' },
  { value: 'Agutayan', label: 'Agutayan' },
  { value: 'Angare', label: 'Angare' },
  { value: 'Anjawan', label: 'Anjawan' },
  { value: 'Baac', label: 'Baac' },
  { value: 'Bagongbong', label: 'Bagongbong' },
  { value: 'Balangigan', label: 'Balangigan' },
  { value: 'Balingasag', label: 'Balingasag' },
  { value: 'Banugan', label: 'Banugan' },
  { value: 'Batuan', label: 'Batuan' },
  { value: 'Bita', label: 'Bita' },
  { value: 'Buenavista', label: 'Buenavista' },
  {
    value: 'Aurora-del Pilar (Poblacion)',
    label: 'Aurora-del Pilar (Poblacion)',
  },
  { value: 'Bacay', label: 'Bacay' },
  { value: 'Bacong', label: 'Bacong' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Balud', label: 'Balud' },
  { value: 'Bantud', label: 'Bantud' },
  { value: 'Bantud Fabrica', label: 'Bantud Fabrica' },
  { value: 'Baras', label: 'Baras' },
  { value: 'Barasan', label: 'Barasan' },
  { value: 'Bayas (Bayas Island)', label: 'Bayas (Bayas Island)' },
  { value: 'Bayuyan', label: 'Bayuyan' },
  { value: 'Botongon', label: 'Botongon' },
  { value: 'Bulaqueña', label: 'Bulaqueña' },
  { value: 'Calapdan', label: 'Calapdan' },
  { value: 'Cano-an', label: 'Cano-an' },
  { value: 'Daan Banua', label: 'Daan Banua' },
  { value: 'Daculan', label: 'Daculan' },
  { value: 'Gogo', label: 'Gogo' },
  { value: 'Jolog', label: 'Jolog' },
  {
    value: 'Loguingot (Loguingot Island)',
    label: 'Loguingot (Loguingot Island)',
  },
  { value: 'Lonoy (Roman Mosqueda)', label: 'Lonoy (Roman Mosqueda)' },
  { value: 'Lumbia (Ana Cuenca)', label: 'Lumbia (Ana Cuenca)' },
  { value: 'Anono-o', label: 'Anono-o' },
  { value: 'Bacong', label: 'Bacong' },
  {
    value: 'Bagumbayan Poblacion (Bagumbayan-Granada)',
    label: 'Bagumbayan Poblacion (Bagumbayan-Granada)',
  },
  {
    value: 'Balantad-Carlos Fruto (Poblacion)',
    label: 'Balantad-Carlos Fruto (Poblacion)',
  },
  { value: 'Baras', label: 'Baras' },
  { value: 'Binanua-an', label: 'Binanua-an' },
  { value: 'Bongol San Miguel', label: 'Bongol San Miguel' },
  { value: 'Bongol San Vicente', label: 'Bongol San Vicente' },
  { value: 'Alameda', label: 'Alameda' },
  { value: 'Amorogtong', label: 'Amorogtong' },
  { value: 'Anilawan', label: 'Anilawan' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Bagacayan', label: 'Bagacayan' },
  { value: 'Bagay', label: 'Bagay' },
  { value: 'Balibagan', label: 'Balibagan' },
  { value: 'Barangay 1 Poblacion', label: 'Barangay 1 Poblacion' },
  { value: 'Barangay 2 Poblacion', label: 'Barangay 2 Poblacion' },
  { value: 'Barangay 3 Poblacion', label: 'Barangay 3 Poblacion' },
  { value: 'Barangay 4 Poblacion', label: 'Barangay 4 Poblacion' },
  { value: 'Barangay 5 Poblacion', label: 'Barangay 5 Poblacion' },
  { value: 'Barangay 6 Poblacion', label: 'Barangay 6 Poblacion' },
  { value: 'Abangay', label: 'Abangay' },
  { value: 'Agcarope', label: 'Agcarope' },
  { value: 'Aglobong', label: 'Aglobong' },
  { value: 'Aguingay', label: 'Aguingay' },
  { value: 'Anhawan', label: 'Anhawan' },
  {
    value: 'Aquino Nobleza East (Poblacion)',
    label: 'Aquino Nobleza East (Poblacion)',
  },
  {
    value: 'Aquino Nobleza West (Poblacion)',
    label: 'Aquino Nobleza West (Poblacion)',
  },
  { value: 'Atimonan', label: 'Atimonan' },
  { value: 'Balanac', label: 'Balanac' },
  { value: 'Barasalon', label: 'Barasalon' },
  { value: 'Bongol', label: 'Bongol' },
  { value: 'Agsirab', label: 'Agsirab' },
  { value: 'Agtuman', label: 'Agtuman' },
  { value: 'Alugmawa', label: 'Alugmawa' },
  { value: 'Badiangan', label: 'Badiangan' },
  { value: 'Balagiao', label: 'Balagiao' },
  { value: 'Banban', label: 'Banban' },
  { value: 'Bansag', label: 'Bansag' },
  { value: 'Bayuco', label: 'Bayuco' },
  { value: 'Binaba-an Armada', label: 'Binaba-an Armada' },
  { value: 'Binaba-an Labayno', label: 'Binaba-an Labayno' },
  { value: 'Binaba-an Limoso', label: 'Binaba-an Limoso' },
  { value: 'Binaba-an Portigo', label: 'Binaba-an Portigo' },
  { value: 'Binaba-an Tirador', label: 'Binaba-an Tirador' },
  { value: 'Bigke', label: 'Bigke' },
  { value: 'Buntatala', label: 'Buntatala' },
  { value: 'Cagamutan Norte', label: 'Cagamutan Norte' },
  { value: 'Cagamutan Sur', label: 'Cagamutan Sur' },
  { value: 'Calaboa', label: 'Calaboa' },
  { value: 'Camangay', label: 'Camangay' },
  { value: 'Cari Mayor', label: 'Cari Mayor' },
  { value: 'Cari Minor', label: 'Cari Minor' },
  { value: 'Gua-an', label: 'Gua-an' },
  { value: 'Guihaman', label: 'Guihaman' },
  { value: 'Guinobatan', label: 'Guinobatan' },
  { value: 'Agpipili', label: 'Agpipili' },
  { value: 'Alcantara', label: 'Alcantara' },
  { value: 'Almeñana', label: 'Almeñana' },
  { value: 'Anabo', label: 'Anabo' },
  { value: 'Bankal', label: 'Bankal' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Cabantohan', label: 'Cabantohan' },
  { value: 'Capiñahan', label: 'Capiñahan' },
  { value: 'Dalipe', label: 'Dalipe' },
  { value: 'Abilay', label: 'Abilay' },
  { value: 'Abay', label: 'Abay' },
  {
    value: 'AGROCEL Poblacion (Aguinaldo-Roxas-Celso Mayor)',
    label: 'AGROCEL Poblacion (Aguinaldo-Roxas-Celso Mayor)',
  },
  { value: 'Amerang', label: 'Amerang' },
  { value: 'Bagacay East', label: 'Bagacay East' },
  { value: 'Bagacay West', label: 'Bagacay West' },
  { value: 'Bolo', label: 'Bolo' },
  { value: 'Bug-ot', label: 'Bug-ot' },
  { value: 'Bulay', label: 'Bulay' },
  { value: 'Buntalan', label: 'Buntalan' },
  { value: 'Agdahon', label: 'Agdahon' },
  { value: 'Agdayao', label: 'Agdayao' },
  { value: 'Aglalana', label: 'Aglalana' },
  { value: 'Agtabo', label: 'Agtabo' },
  { value: 'Agtambo', label: 'Agtambo' },
  { value: 'Agdum', label: 'Agdum' },
  { value: 'Aguiauan', label: 'Aguiauan' },
  { value: 'Alimodias', label: 'Alimodias' },
  { value: 'Awang', label: 'Awang' },
  { value: 'Abat', label: 'Abat' },
  { value: 'Agmanaphao', label: 'Agmanaphao' },
  { value: 'Amiroy', label: 'Amiroy' },
  { value: 'Baclayan', label: 'Baclayan' },
  { value: 'Badiang', label: 'Badiang' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Bilidan', label: 'Bilidan' },
  { value: 'Abilay Norte', label: 'Abilay Norte' },
  { value: 'Abilay Sur', label: 'Abilay Sur' },
  { value: 'Alegre', label: 'Alegre' },
  { value: 'Batuan Ilaud', label: 'Batuan Ilaud' },
  { value: 'Batuan Ilaya', label: 'Batuan Ilaya' },
  { value: 'Bita Norte', label: 'Bita Norte' },
  { value: 'Aganan', label: 'Aganan' },
  { value: 'Amparo', label: 'Amparo' },
  { value: 'Anilao', label: 'Anilao' },
  { value: 'Balabag', label: 'Balabag' },
  { value: 'Cabugao Norte', label: 'Cabugao Norte' },
  { value: 'Cabugao Sur', label: 'Cabugao Sur' },
  { value: 'Jibao-an', label: 'Jibao-an' },
  { value: 'Mali-ao', label: 'Mali-ao' },
  { value: 'Abangay', label: 'Abangay' },
  { value: 'Amamaros', label: 'Amamaros' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Barasan', label: 'Barasan' },
  { value: 'Batuan', label: 'Batuan' },
  { value: 'Bongco', label: 'Bongco' },
  { value: 'Primitivo Ledesma Ward', label: 'Primitivo Ledesma Ward' },
  { value: 'Agdaliran', label: 'Agdaliran' },
  { value: 'Amayong', label: 'Amayong' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Batuan', label: 'Batuan' },
  { value: 'Bondulan', label: 'Bondulan' },
  { value: 'Boroñgon', label: 'Boroñgon' },
  { value: 'Canas', label: 'Canas' },
  { value: 'Capinang', label: 'Capinang' },
  { value: 'Cubay', label: 'Cubay' },
  { value: 'Abaca', label: 'Abaca' },
  { value: 'Asisig', label: 'Asisig' },
  { value: 'Bantayan', label: 'Bantayan' },
  { value: 'Braulan', label: 'Braulan' },
  { value: 'Cabugao Nuevo', label: 'Cabugao Nuevo' },
  { value: 'Cabugao Viejo', label: 'Cabugao Viejo' },
  { value: 'Camiri', label: 'Camiri' },
  { value: 'Catan-Agan', label: 'Catan-Agan' },
  { value: 'Compo', label: 'Compo' },
  { value: 'Cubay', label: 'Cubay' },
  { value: 'Amboyu-an', label: 'Amboyu-an' },
  { value: 'Andres Bonifacio', label: 'Andres Bonifacio' },
  { value: 'Antalon', label: 'Antalon' },
  { value: 'Bad-as', label: 'Bad-as' },
  { value: 'Bagumbayan', label: 'Bagumbayan' },
  { value: 'Balabago', label: 'Balabago' },
  { value: 'Baybay', label: 'Baybay' },
  { value: 'Mangorocoro', label: 'Mangorocoro' },
  { value: 'Nasidman', label: 'Nasidman' },
  { value: 'Pantalan Nabaye', label: 'Pantalan Nabaye' },
  { value: 'Pantalan Navarro', label: 'Pantalan Navarro' },
  { value: 'Pedada', label: 'Pedada' },
  { value: 'Pili', label: 'Pili' },
  { value: 'Pinantan Diel', label: 'Pinantan Diel' },
  { value: 'Pinantan Elizalde', label: 'Pinantan Elizalde' },
  { value: 'Pinay Espinosa', label: 'Pinay Espinosa' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Progreso', label: 'Progreso' },
  { value: 'Puente Bunglas', label: 'Puente Bunglas' },
  { value: 'Punta Buri', label: 'Punta Buri' },
  { value: 'Rojas', label: 'Rojas' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'Santo Rosario', label: 'Santo Rosario' },
  { value: 'Silagon', label: 'Silagon' },
  { value: 'Tagubanhan', label: 'Tagubanhan' },
  { value: 'Taguhangin', label: 'Taguhangin' },
  { value: 'Tanduyan', label: 'Tanduyan' },
  { value: 'Tipacla', label: 'Tipacla' },
  { value: 'Tubogan', label: 'Tubogan' },
  { value: 'Ba?ong', label: 'Ba?ong' },
  { value: 'Binalud', label: 'Binalud' },
  { value: 'Bugang', label: 'Bugang' },
  { value: 'Buhay', label: 'Buhay' },
  { value: 'Bulod', label: 'Bulod' },
  { value: 'Cabacanan Proper', label: 'Cabacanan Proper' },
  { value: 'Cabacanan Rizal', label: 'Cabacanan Rizal' },
  { value: 'Cagay', label: 'Cagay' },
  { value: 'Coline', label: 'Coline' },
  { value: 'Coline-Dalag', label: 'Coline-Dalag' },
  { value: 'Cunsad', label: 'Cunsad' },
  { value: 'Cuyad', label: 'Cuyad' },
  { value: 'Dalid', label: 'Dalid' },
  { value: 'Dao', label: 'Dao' },
  { value: 'Gines', label: 'Gines' },
  { value: 'Ginomoy', label: 'Ginomoy' },
  { value: 'Ingwan', label: 'Ingwan' },
  { value: 'Laylayan', label: 'Laylayan' },
  { value: 'Lico', label: 'Lico' },
  { value: 'Luan-luan', label: 'Luan-luan' },
  { value: 'Malamboy-Bondolan', label: 'Malamboy-Bondolan' },
  { value: 'Malamhay', label: 'Malamhay' },
  { value: 'Mambawi', label: 'Mambawi' },
  { value: 'Manasa', label: 'Manasa' },
  { value: 'Manduyog', label: 'Manduyog' },
  { value: 'Pajo', label: 'Pajo' },
  { value: 'Pianda-an Norte', label: 'Pianda-an Norte' },
  { value: 'Pianda-an Sur', label: 'Pianda-an Sur' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Punong', label: 'Punong' },
  { value: 'Quinaspan', label: 'Quinaspan' },
  { value: 'Sinamay', label: 'Sinamay' },
  { value: 'Sulong', label: 'Sulong' },
  { value: 'Taban?Manguining', label: 'Taban?Manguining' },
  { value: 'Tabug', label: 'Tabug' },
  { value: 'Tarug', label: 'Tarug' },
  { value: 'Tugaslon', label: 'Tugaslon' },
  { value: 'Ubodan', label: 'Ubodan' },
  { value: 'Ugbo', label: 'Ugbo' },
  { value: 'Ulay Bugang', label: 'Ulay Bugang' },
  { value: 'Ulay Hinablan', label: 'Ulay Hinablan' },
  { value: 'Umingan', label: 'Umingan' },
  { value: 'Mostro', label: 'Mostro' },
  { value: 'Palaypay', label: 'Palaypay' },
  { value: 'Pantalan', label: 'Pantalan' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Sambag Culob', label: 'Sambag Culob' },
  { value: 'San Carlos', label: 'San Carlos' },
  { value: 'San Juan Crisostomo', label: 'San Juan Crisostomo' },
  { value: 'Santa Rita', label: 'Santa Rita' },
  { value: 'Santo Rosario', label: 'Santo Rosario' },
  { value: 'Serallo', label: 'Serallo' },
  { value: 'Vista Alegre', label: 'Vista Alegre' },
  { value: 'Guinawahan', label: 'Guinawahan' },
  { value: 'Ilongbukid', label: 'Ilongbukid' },
  { value: 'Indorohan', label: 'Indorohan' },
  { value: 'Iniligan', label: 'Iniligan' },
  { value: 'Latawan', label: 'Latawan' },
  { value: 'Linayuan', label: 'Linayuan' },
  { value: 'Mainguit', label: 'Mainguit' },
  { value: 'Malublub', label: 'Malublub' },
  { value: 'Manaolan', label: 'Manaolan' },
  { value: 'Mapili Grande', label: 'Mapili Grande' },
  { value: 'Mapili Sanjo', label: 'Mapili Sanjo' },
  { value: 'Odiongan', label: 'Odiongan' },
  { value: 'Poblacion (Badiangan)', label: 'Poblacion (Badiangan)' },
  { value: 'San Julian', label: 'San Julian' },
  { value: 'Sariri', label: 'Sariri' },
  { value: 'Sianon', label: 'Sianon' },
  { value: 'Sinuagan', label: 'Sinuagan' },
  { value: 'Talaba', label: 'Talaba' },
  { value: 'Tamocol', label: 'Tamocol' },
  { value: 'Teneclan', label: 'Teneclan' },
  { value: 'Tina', label: 'Tina' },
  { value: 'Ipil', label: 'Ipil' },
  { value: 'Kinalkalan', label: 'Kinalkalan' },
  { value: 'Lawis', label: 'Lawis' },
  { value: 'Malapoc', label: 'Malapoc' },
  { value: 'Mamhut Norte', label: 'Mamhut Norte' },
  { value: 'Mamhut Sur', label: 'Mamhut Sur' },
  { value: 'Maya', label: 'Maya' },
  { value: 'Pani?an', label: 'Pani?an' },
  { value: 'Poblacion Norte', label: 'Poblacion Norte' },
  { value: 'Poblacion Sur', label: 'Poblacion Sur' },
  { value: 'Quiasan', label: 'Quiasan' },
  { value: 'Salong', label: 'Salong' },
  { value: 'Salvacion', label: 'Salvacion' },
  { value: 'Tingui?an', label: 'Tingui?an' },
  { value: 'Zaragosa', label: 'Zaragosa' },
  { value: 'Juanico', label: 'Juanico' },
  { value: 'Libertad', label: 'Libertad' },
  { value: 'Magdalo', label: 'Magdalo' },
  { value: 'Managopaya', label: 'Managopaya' },
  { value: 'Merced', label: 'Merced' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'San Salvador', label: 'San Salvador' },
  { value: 'Talokgangan', label: 'Talokgangan' },
  { value: 'Zona Sur', label: 'Zona Sur' },
  { value: 'Lagubang', label: 'Lagubang' },
  { value: 'Lanas', label: 'Lanas' },
  { value: 'Lico?an', label: 'Lico?an' },
  { value: 'Linao', label: 'Linao' },
  { value: 'Monpon', label: 'Monpon' },
  { value: 'Palaciawan', label: 'Palaciawan' },
  { value: 'Patag', label: 'Patag' },
  { value: 'Salihid', label: 'Salihid' },
  { value: 'Sohoton', label: 'Sohoton' },
  { value: 'So?ol', label: 'So?ol' },
  { value: 'Tabucan', label: 'Tabucan' },
  { value: 'Tabuc?Suba', label: 'Tabuc?Suba' },
  { value: 'Talisay', label: 'Talisay' },
  { value: 'Tinorian', label: 'Tinorian' },
  { value: 'Tiwi', label: 'Tiwi' },
  { value: 'Tubungan', label: 'Tubungan' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Puerto Princesa', label: 'Puerto Princesa' },
  { value: 'Rizal', label: 'Rizal' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'San Fernando', label: 'San Fernando' },
  { value: 'San Francisco', label: 'San Francisco' },
  { value: 'San Geronimo', label: 'San Geronimo' },
  { value: 'San Juan', label: 'San Juan' },
  { value: 'San Lucas', label: 'San Lucas' },
  { value: 'San Miguel', label: 'San Miguel' },
  { value: 'San Roque', label: 'San Roque' },
  { value: 'Santiago', label: 'Santiago' },
  { value: 'Santo Domingo', label: 'Santo Domingo' },
  { value: 'Santo Tomas', label: 'Santo Tomas' },
  { value: 'Ugasan', label: 'Ugasan' },
  { value: 'Vista Alegre', label: 'Vista Alegre' },
  { value: 'Hamod', label: 'Hamod' },
  { value: 'Malico', label: 'Malico' },
  { value: 'Nangka', label: 'Nangka' },
  { value: 'Pasayan', label: 'Pasayan' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Quiazan Florete', label: 'Quiazan Florete' },
  { value: 'Quiazan Lopez', label: 'Quiazan Lopez' },
  { value: 'Salong', label: 'Salong' },
  { value: 'Santa Ana', label: 'Santa Ana' },
  { value: 'Tanao', label: 'Tanao' },
  { value: 'Tapi?an', label: 'Tapi?an' },
  { value: 'Gaub', label: 'Gaub' },
  { value: 'Gines Interior', label: 'Gines Interior' },
  { value: 'Gines Patag', label: 'Gines Patag' },
  { value: 'Guibuangan Tigbauan', label: 'Guibuangan Tigbauan' },
  { value: 'Inabasan', label: 'Inabasan' },
  { value: 'Inaca', label: 'Inaca' },
  { value: 'Inaladan', label: 'Inaladan' },
  { value: 'Ingas', label: 'Ingas' },
  { value: 'Ito Norte', label: 'Ito Norte' },
  { value: 'Ito Sur', label: 'Ito Sur' },
  { value: 'Janipaan Central', label: 'Janipaan Central' },
  { value: 'Janipaan Este', label: 'Janipaan Este' },
  { value: 'Janipaan Oeste', label: 'Janipaan Oeste' },
  { value: 'Janipaan Olo', label: 'Janipaan Olo' },
  { value: 'Jelicuon Lusaya', label: 'Jelicuon Lusaya' },
  { value: 'Jelicuon Montinola', label: 'Jelicuon Montinola' },
  { value: 'Lag?an', label: 'Lag?an' },
  { value: 'Leong', label: 'Leong' },
  { value: 'Lutac', label: 'Lutac' },
  { value: 'Manguna', label: 'Manguna' },
  { value: 'Maraguit', label: 'Maraguit' },
  { value: 'Morubuan', label: 'Morubuan' },
  { value: 'Pacatin', label: 'Pacatin' },
  { value: 'Pagotpot', label: 'Pagotpot' },
  { value: 'Pamul?Ogan', label: 'Pamul?Ogan' },
  { value: 'Pamuringao Garrido', label: 'Pamuringao Garrido' },
  { value: 'Pamuringao Proper', label: 'Pamuringao Proper' },
  { value: 'Pungtod', label: 'Pungtod' },
  { value: 'Puyas', label: 'Puyas' },
  { value: 'Salacay', label: 'Salacay' },
  { value: 'Sulanga', label: 'Sulanga' },
  { value: 'Tabucan', label: 'Tabucan' },
  { value: 'Tacdangan', label: 'Tacdangan' },
  { value: 'Talanghauan', label: 'Talanghauan' },
  { value: 'Tigbauan Road', label: 'Tigbauan Road' },
  { value: 'Tinio?an', label: 'Tinio?an' },
  { value: 'Tiring', label: 'Tiring' },
  { value: 'Tupol Central', label: 'Tupol Central' },
  { value: 'Tupol Este', label: 'Tupol Este' },
  { value: 'Tupol Oeste', label: 'Tupol Oeste' },
  { value: 'Tuy?an', label: 'Tuy?an' },
  {
    value: 'Zone I Poblacion (Barangay 1)',
    label: 'Zone I Poblacion (Barangay 1)',
  },
  {
    value: 'Zone II Poblacion (Barangay 2)',
    label: 'Zone II Poblacion (Barangay 2)',
  },
  {
    value: 'Zone III Poblacion (Barangay 3)',
    label: 'Zone III Poblacion (Barangay 3)',
  },
  {
    value: 'Zone IV Poblacion (Barangay 4)',
    label: 'Zone IV Poblacion (Barangay 4)',
  },
  {
    value: 'Zone IX Poblacion (Barangay 9)',
    label: 'Zone IX Poblacion (Barangay 9)',
  },
  {
    value: 'Zone V Poblacion (Barangay 5)',
    label: 'Zone V Poblacion (Barangay 5)',
  },
  {
    value: 'Zone VI Poblacion (Barangay 6)',
    label: 'Zone VI Poblacion (Barangay 6)',
  },
  {
    value: 'Zone VII Poblacion (Barangay 7)',
    label: 'Zone VII Poblacion (Barangay 7)',
  },
  {
    value: 'Zone VIII Poblacion (Barangay 8)',
    label: 'Zone VIII Poblacion (Barangay 8)',
  },
  {
    value: 'Zone X Poblacion (Barangay 10)',
    label: 'Zone X Poblacion (Barangay 10)',
  },
  {
    value: 'Zone XI Poblacion (Barangay 11)',
    label: 'Zone XI Poblacion (Barangay 11)',
  },
  { value: 'Barrio Calinog', label: 'Barrio Calinog' },
  { value: 'Binolosan Grande', label: 'Binolosan Grande' },
  { value: 'Binolosan Peque?o', label: 'Binolosan Peque?o' },
  { value: 'Cabagiao', label: 'Cabagiao' },
  { value: 'Cabugao', label: 'Cabugao' },
  { value: 'Cahigon', label: 'Cahigon' },
  { value: 'Camalongo', label: 'Camalongo' },
  { value: 'Canabajan', label: 'Canabajan' },
  { value: 'Caratagan', label: 'Caratagan' },
  { value: 'Carvasana', label: 'Carvasana' },
  { value: 'Dalid', label: 'Dalid' },
  { value: 'Datagan', label: 'Datagan' },
  { value: 'Gama Grande', label: 'Gama Grande' },
  { value: 'Gama Peque?o', label: 'Gama Peque?o' },
  { value: 'Garangan', label: 'Garangan' },
  { value: 'Guinbonyugan', label: 'Guinbonyugan' },
  { value: 'Guiso', label: 'Guiso' },
  { value: 'Hilwan', label: 'Hilwan' },
  { value: 'Impalidan', label: 'Impalidan' },
  { value: 'Ipil', label: 'Ipil' },
  { value: 'Jamin?ay', label: 'Jamin?ay' },
  { value: 'Lampaya', label: 'Lampaya' },
  { value: 'Libot', label: 'Libot' },
  { value: 'Lonoy', label: 'Lonoy' },
  { value: 'Malag?it', label: 'Malag?it' },
  { value: 'Malaguinabot', label: 'Malaguinabot' },
  { value: 'Malapawe', label: 'Malapawe' },
  { value: 'Malitbog Centro', label: 'Malitbog Centro' },
  { value: 'Mambiranan', label: 'Mambiranan' },
  { value: 'Manaripay', label: 'Manaripay' },
  { value: 'Marandig', label: 'Marandig' },
  { value: 'Masaroy', label: 'Masaroy' },
  { value: 'Maspasan', label: 'Maspasan' },
  { value: 'Nalbugan', label: 'Nalbugan' },
  { value: 'Owak', label: 'Owak' },
  { value: 'Poblacion Centro', label: 'Poblacion Centro' },
  { value: 'Poblacion Delgado', label: 'Poblacion Delgado' },
  { value: 'Poblacion Ilaya', label: 'Poblacion Ilaya' },
  { value: 'Poblacion Rizal Ilaud', label: 'Poblacion Rizal Ilaud' },
  { value: 'San Nicolas', label: 'San Nicolas' },
  { value: 'Simsiman', label: 'Simsiman' },
  { value: 'Supanga', label: 'Supanga' },
  { value: 'Tabucan', label: 'Tabucan' },
  { value: 'Tahing', label: 'Tahing' },
  { value: 'Tibiao', label: 'Tibiao' },
  { value: 'Tigbayog', label: 'Tigbayog' },
  { value: 'Toyungan', label: 'Toyungan' },
  { value: 'Ulayan', label: 'Ulayan' },
  { value: 'Cabilao Peque?o', label: 'Cabilao Peque?o' },
  { value: 'Cabuguana', label: 'Cabuguana' },
  { value: 'Cawayan', label: 'Cawayan' },
  { value: 'Dayhagan', label: 'Dayhagan' },
  { value: 'Gabi', label: 'Gabi' },
  { value: 'Granada', label: 'Granada' },
  { value: 'Guinticgan', label: 'Guinticgan' },
  { value: 'Isla de Cana', label: 'Isla de Cana' },
  { value: 'Lantangan', label: 'Lantangan' },
  { value: 'Manlot', label: 'Manlot' },
  { value: 'Nalumsan', label: 'Nalumsan' },
  { value: 'Pantalan', label: 'Pantalan' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Punta (Bolocawe)', label: 'Punta (Bolocawe)' },
  { value: 'Punta Batuanan', label: 'Punta Batuanan' },
  { value: 'San Fernando', label: 'San Fernando' },
  { value: 'Tabugon', label: 'Tabugon' },
  { value: 'Talingting', label: 'Talingting' },
  { value: 'Tarong', label: 'Tarong' },
  { value: 'Tinigban', label: 'Tinigban' },
  { value: 'Tupaz', label: 'Tupaz' },
  { value: 'Lo?ong', label: 'Lo?ong' },
  { value: 'Macalbang', label: 'Macalbang' },
  { value: 'Macatunao', label: 'Macatunao' },
  { value: 'Malangabang', label: 'Malangabang' },
  { value: 'Maliogliog', label: 'Maliogliog' },
  { value: 'Ni?o', label: 'Ni?o' },
  { value: 'Nipa', label: 'Nipa' },
  { value: 'Plandico', label: 'Plandico' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Polopina', label: 'Polopina' },
  { value: 'Salvacion', label: 'Salvacion' },
  { value: 'Talotu?an', label: 'Talotu?an' },
  { value: 'Tambaliza', label: 'Tambaliza' },
  { value: 'Tamis?ac', label: 'Tamis?ac' },
  { value: 'Ginalinan Nuevo', label: 'Ginalinan Nuevo' },
  { value: 'Ginalinan Viejo', label: 'Ginalinan Viejo' },
  { value: 'Gutao', label: 'Gutao' },
  { value: 'Ilajas', label: 'Ilajas' },
  { value: 'Libo?o', label: 'Libo?o' },
  { value: 'Licu?an', label: 'Licu?an' },
  { value: 'Lincud', label: 'Lincud' },
  { value: 'Matangharon', label: 'Matangharon' },
  { value: 'Moroboro', label: 'Moroboro' },
  { value: 'Namatay', label: 'Namatay' },
  { value: 'Nazuni', label: 'Nazuni' },
  { value: 'Pandan', label: 'Pandan' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Potolan', label: 'Potolan' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'San Matias', label: 'San Matias' },
  { value: 'Siniba?an', label: 'Siniba?an' },
  { value: 'Tabugon', label: 'Tabugon' },
  { value: 'Tambunac', label: 'Tambunac' },
  { value: 'Tanghawan', label: 'Tanghawan' },
  { value: 'Tiguib', label: 'Tiguib' },
  { value: 'Tinocuan', label: 'Tinocuan' },
  { value: 'Tulatula?an', label: 'Tulatula?an' },
  { value: 'Bugtongan', label: 'Bugtongan' },
  { value: 'Cabudian', label: 'Cabudian' },
  { value: 'Calaca?an', label: 'Calaca?an' },
  { value: 'Calang', label: 'Calang' },
  { value: 'Calawinan', label: 'Calawinan' },
  { value: 'Capaycapay', label: 'Capaycapay' },
  { value: 'Capuling', label: 'Capuling' },
  { value: 'Catig', label: 'Catig' },
  { value: 'Dila?an', label: 'Dila?an' },
  { value: 'Fundacion', label: 'Fundacion' },
  { value: 'Inadlawan', label: 'Inadlawan' },
  { value: 'Jagdong', label: 'Jagdong' },
  { value: 'Jaguimit', label: 'Jaguimit' },
  { value: 'Lacadon', label: 'Lacadon' },
  { value: 'Luag', label: 'Luag' },
  { value: 'Malusgod', label: 'Malusgod' },
  { value: 'Maribuyong', label: 'Maribuyong' },
  { value: 'Minanga', label: 'Minanga' },
  { value: 'Monpon', label: 'Monpon' },
  { value: 'Navalas', label: 'Navalas' },
  { value: 'Pader', label: 'Pader' },
  { value: 'Pandan', label: 'Pandan' },
  { value: 'Poblacion A', label: 'Poblacion A' },
  { value: 'Poblacion B', label: 'Poblacion B' },
  { value: 'Poblacion C', label: 'Poblacion C' },
  { value: 'Poblacion D', label: 'Poblacion D' },
  { value: 'Ponong Grande', label: 'Ponong Grande' },
  { value: 'Ponong Peque?o', label: 'Ponong Peque?o' },
  { value: 'Purog', label: 'Purog' },
  { value: 'Romblon', label: 'Romblon' },
  { value: 'San Isidro', label: 'San Isidro' },
  { value: 'Santo Ni?o', label: 'Santo Ni?o' },
  { value: 'Sawe', label: 'Sawe' },
  { value: 'Taminla', label: 'Taminla' },
  { value: 'Tinocuan', label: 'Tinocuan' },
  { value: 'Tipolo', label: 'Tipolo' },
  {
    value: 'Basa?Mabini Bonifacio (Poblacion)',
    label: 'Basa?Mabini Bonifacio (Poblacion)',
  },
  { value: 'Bolilao', label: 'Bolilao' },
  {
    value: 'Buenaflor Embarkadero (Poblacion)',
    label: 'Buenaflor Embarkadero (Poblacion)',
  },
  { value: 'Burgos?Regidor (Poblacion)', label: 'Burgos?Regidor (Poblacion)' },
  { value: 'Calao', label: 'Calao' },
  { value: 'Cali', label: 'Cali' },
  { value: 'Cansilayan', label: 'Cansilayan' },
  { value: 'Capaliz', label: 'Capaliz' },
  { value: 'Cayos', label: 'Cayos' },
  { value: 'Compayan', label: 'Compayan' },
  { value: 'Dacutan', label: 'Dacutan' },
  { value: 'Ermita', label: 'Ermita' },
  { value: 'Ilaya 1st', label: 'Ilaya 1st' },
  { value: 'Ilaya 2nd', label: 'Ilaya 2nd' },
  { value: 'Ilaya 3rd', label: 'Ilaya 3rd' },
  { value: 'Jardin', label: 'Jardin' },
  { value: 'Lacturan', label: 'Lacturan' },
  {
    value: 'Lopez Jaena?Rizal (Poblacion)',
    label: 'Lopez Jaena?Rizal (Poblacion)',
  },
  { value: 'Managuit', label: 'Managuit' },
  { value: 'Maquina', label: 'Maquina' },
  { value: 'Nanding Lopez', label: 'Nanding Lopez' },
  { value: 'Pagdugue', label: 'Pagdugue' },
  { value: 'Paloc Bigque', label: 'Paloc Bigque' },
  { value: 'Paloc Sool', label: 'Paloc Sool' },
  { value: 'Patlad', label: 'Patlad' },
  { value: 'Pd Monfort North (Lublub)', label: 'Pd Monfort North (Lublub)' },
  {
    value: 'Pd Monfort South (Guinsampanan)',
    label: 'Pd Monfort South (Guinsampanan)',
  },
  { value: 'Pulao', label: 'Pulao' },
  { value: 'Rosario', label: 'Rosario' },
  { value: 'Sapao', label: 'Sapao' },
  { value: 'Sulangan', label: 'Sulangan' },
  { value: 'Tabucan', label: 'Tabucan' },
  { value: 'Talusan', label: 'Talusan' },
  { value: 'Tambobo', label: 'Tambobo' },
  { value: 'Tamboilan', label: 'Tamboilan' },
  { value: 'Victorias', label: 'Victorias' },
  { value: 'Malbog', label: 'Malbog' },
  { value: 'Manipulon', label: 'Manipulon' },
  { value: 'Pa-on', label: 'Pa-on' },
  { value: 'Poblacion Zone 1', label: 'Poblacion Zone 1' },
  { value: 'Poblacion Zone II', label: 'Poblacion Zone II' },
  { value: 'Poblacion Zone III', label: 'Poblacion Zone III' },
  { value: 'San Roque', label: 'San Roque' },
  { value: 'Santa Ana', label: 'Santa Ana' },
  { value: 'Tabu-an', label: 'Tabu-an' },
  { value: 'Tacbuyan', label: 'Tacbuyan' },
  { value: 'Tanza', label: 'Tanza' },
  { value: 'Villa Pani-an', label: 'Villa Pani-an' },
  { value: 'Bulad', label: 'Bulad' },
  { value: 'Buluangan', label: 'Buluangan' },
  { value: 'Burgos-Gengos (Poblacion)', label: 'Burgos-Gengos (Poblacion)' },
  { value: 'Cabasi', label: 'Cabasi' },
  { value: 'Cabubugan', label: 'Cabubugan' },
  { value: 'Calampitao', label: 'Calampitao' },
  { value: 'Camangahan', label: 'Camangahan' },
  {
    value: 'Generosa-Cristobal Colon (Poblacion)',
    label: 'Generosa-Cristobal Colon (Poblacion)',
  },
  { value: 'Gerona-Gimeno (Poblacion)', label: 'Gerona-Gimeno (Poblacion)' },
  {
    value: 'Girado-Magsaysay (Poblacion)',
    label: 'Girado-Magsaysay (Poblacion)',
  },
  { value: 'Gotera (Poblacion)', label: 'Gotera (Poblacion)' },
  { value: 'Igcocolo', label: 'Igcocolo' },
  { value: 'Iyasan', label: 'Iyasan' },
  {
    value: 'Libo-on Gonzales (Poblacion)',
    label: 'Libo-on Gonzales (Poblacion)',
  },
  { value: 'Lubacan', label: 'Lubacan' },
  { value: 'Nahapay', label: 'Nahapay' },
  { value: 'Nalundan', label: 'Nalundan' },
  { value: 'Nanga', label: 'Nanga' },
  { value: 'Nito-an Lupsag', label: 'Nito-an Lupsag' },
  { value: 'Particion', label: 'Particion' },
  { value: 'Pescadores (Poblacion)', label: 'Pescadores (Poblacion)' },
  { value: 'Rizal-Tuguisan (Poblacion)', label: 'Rizal-Tuguisan (Poblacion)' },
  { value: 'Santa Rosa-Laguna', label: 'Santa Rosa-Laguna' },
  { value: 'Sipitan-Badiang', label: 'Sipitan-Badiang' },
  {
    value: 'Torreblanca?Blumentritt (Poblacion)',
    label: 'Torreblanca?Blumentritt (Poblacion)',
  },
  { value: 'Barasan', label: 'Barasan' },
  { value: 'Binanua-an', label: 'Binanua-an' },
  { value: 'Boclod', label: 'Boclod' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Buga', label: 'Buga' },
  { value: 'Bugnay', label: 'Bugnay' },
  { value: 'Calampitao', label: 'Calampitao' },
  { value: 'Cale', label: 'Cale' },
  { value: 'Catiringan', label: 'Catiringan' },
  { value: 'Corucuan', label: 'Corucuan' },
  { value: 'Igcabugao', label: 'Igcabugao' },
  { value: 'Igpigus', label: 'Igpigus' },
  { value: 'Igtalongon', label: 'Igtalongon' },
  { value: 'Indaluyon', label: 'Indaluyon' },
  { value: 'Jovellar', label: 'Jovellar' },
  { value: 'Kinagdan', label: 'Kinagdan' },
  { value: 'Lab-on', label: 'Lab-on' },
  { value: 'Lacay Dol-Dol', label: 'Lacay Dol-Dol' },
  { value: 'Lumangan', label: 'Lumangan' },
  { value: 'Lutungan', label: 'Lutungan' },
  { value: 'Mantangon', label: 'Mantangon' },
  { value: 'Mulangan', label: 'Mulangan' },
  { value: 'Pasong', label: 'Pasong' },
  { value: 'Passi', label: 'Passi' },
  { value: 'Pinaopawan', label: 'Pinaopawan' },
  { value: 'Riro-an', label: 'Riro-an' },
  { value: 'San Ambrosio', label: 'San Ambrosio' },
  { value: 'Santa Barbara', label: 'Santa Barbara' },
  { value: 'Signe', label: 'Signe' },
  { value: 'Tabiac', label: 'Tabiac' },
  { value: 'Talayatay', label: 'Talayatay' },
  { value: 'Taytay', label: 'Taytay' },
  { value: 'Tigbanaba', label: 'Tigbanaba' },
  { value: 'Calmay', label: 'Calmay' },
  { value: 'Canawili', label: 'Canawili' },
  { value: 'Canawillian', label: 'Canawillian' },
  {
    value: 'Capt. A. Tirador (Poblacion)',
    label: 'Capt. A. Tirador (Poblacion)',
  },
  { value: 'Caranas', label: 'Caranas' },
  { value: 'Caraudan', label: 'Caraudan' },
  { value: 'Carigangan', label: 'Carigangan' },
  {
    value: 'Concepcion Poblacion (D. G. Abordo)',
    label: 'Concepcion Poblacion (D. G. Abordo)',
  },
  {
    value: 'Crispin Salazar North (Poblacion)',
    label: 'Crispin Salazar North (Poblacion)',
  },
  {
    value: 'Crispin Salazar South (Poblacion)',
    label: 'Crispin Salazar South (Poblacion)',
  },
  { value: 'Cunsad', label: 'Cunsad' },
  { value: 'Dabong', label: 'Dabong' },
  { value: 'Damires', label: 'Damires' },
  { value: 'Damo-ong', label: 'Damo-ong' },
  { value: 'Danao', label: 'Danao' },
  {
    value: 'Don T. Lutero Center (Poblacion)',
    label: 'Don T. Lutero Center (Poblacion)',
  },
  {
    value: 'Don T. Lutero East (Poblacion)',
    label: 'Don T. Lutero East (Poblacion)',
  },
  {
    value: 'Don T. Lutero West Poblacion (Don T. Lutero North)',
    label: 'Don T. Lutero West Poblacion (Don T. Lutero North)',
  },
  { value: 'Gines', label: 'Gines' },
  { value: 'Golgota (Poblacion)', label: 'Golgota (Poblacion)' },
  { value: 'Guadalupe', label: 'Guadalupe' },
  { value: 'Jibolo', label: 'Jibolo' },
  { value: 'Kuyot', label: 'Kuyot' },
  { value: 'Locsin (Poblacion)', label: 'Locsin (Poblacion)' },
  { value: 'Madong', label: 'Madong' },
  { value: 'Manacabac', label: 'Manacabac' },
  { value: 'Mangil', label: 'Mangil' },
  { value: 'Matag-ub', label: 'Matag-ub' },
  { value: 'Monte-Magapa', label: 'Monte-Magapa' },
  { value: 'Pangilihan', label: 'Pangilihan' },
  { value: 'Panuran', label: 'Panuran' },
  { value: 'Pararinga', label: 'Pararinga' },
  { value: 'Patong?patong', label: 'Patong?patong' },
  { value: 'Quipot', label: 'Quipot' },
  { value: 'R. Armada (Poblacion)', label: 'R. Armada (Poblacion)' },
  { value: 'S. M. Villa (Poblacion)', label: 'S. M. Villa (Poblacion)' },
  { value: 'San Julian (Poblacion)', label: 'San Julian (Poblacion)' },
  { value: 'San Pedro (Poblacion)', label: 'San Pedro (Poblacion)' },
  { value: 'Santa Rita (Poblacion)', label: 'Santa Rita (Poblacion)' },
  { value: 'Santo Tomas', label: 'Santo Tomas' },
  { value: 'Sarawag', label: 'Sarawag' },
  { value: 'Tambal', label: 'Tambal' },
  { value: 'Tamu-an', label: 'Tamu-an' },
  { value: 'Tiringanan', label: 'Tiringanan' },
  { value: 'Tolarucan', label: 'Tolarucan' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Ubian', label: 'Ubian' },
  { value: 'Yabon', label: 'Yabon' },
  { value: 'Bogongbong', label: 'Bogongbong' },
  { value: 'Bonbon', label: 'Bonbon' },
  { value: 'Bontoc', label: 'Bontoc' },
  { value: 'Buri', label: 'Buri' },
  { value: 'Burirao', label: 'Burirao' },
  { value: 'Buwang', label: 'Buwang' },
  { value: 'Cabatangan', label: 'Cabatangan' },
  { value: 'Cabugao', label: 'Cabugao' },
  { value: 'Cabunlawan', label: 'Cabunlawan' },
  { value: 'Caguisanan', label: 'Caguisanan' },
  { value: 'Caloy-Ahan', label: 'Caloy-Ahan' },
  { value: 'Caninguan', label: 'Caninguan' },
  { value: 'Capangyan', label: 'Capangyan' },
  { value: 'Cayan Este', label: 'Cayan Este' },
  { value: 'Cayan Oeste', label: 'Cayan Oeste' },
  { value: 'Corot-on', label: 'Corot-on' },
  { value: 'Coto', label: 'Coto' },
  { value: 'Cubay', label: 'Cubay' },
  { value: 'Cunarum', label: 'Cunarum' },
  { value: 'Daanbanwa', label: 'Daanbanwa' },
  { value: 'Gines', label: 'Gines' },
  { value: 'Hipgos', label: 'Hipgos' },
  { value: 'Jayubo', label: 'Jayubo' },
  { value: 'Jorog', label: 'Jorog' },
  { value: 'Lanot Grande', label: 'Lanot Grande' },
  { value: 'Lanot Pequeño', label: 'Lanot Pequeño' },
  { value: 'Legayada', label: 'Legayada' },
  { value: 'Lumanay', label: 'Lumanay' },
  { value: 'Madarag', label: 'Madarag' },
  { value: 'Magbato', label: 'Magbato' },
  { value: 'Maite Grande', label: 'Maite Grande' },
  { value: 'Maite Pequeño', label: 'Maite Pequeño' },
  { value: 'Malag-it', label: 'Malag-it' },
  { value: 'Manaulan', label: 'Manaulan' },
  { value: 'Maribong', label: 'Maribong' },
  { value: 'Marong', label: 'Marong' },
  { value: 'Misi', label: 'Misi' },
  { value: 'Natividad', label: 'Natividad' },
  { value: 'Pajo', label: 'Pajo' },
  { value: 'Pandan', label: 'Pandan' },
  { value: 'Panuran', label: 'Panuran' },
  { value: 'Pasig', label: 'Pasig' },
  { value: 'Patag', label: 'Patag' },
  { value: 'Poblacion Ilawod', label: 'Poblacion Ilawod' },
  { value: 'Poblacion Ilaya', label: 'Poblacion Ilaya' },
  { value: 'Poong', label: 'Poong' },
  { value: 'Pughanan', label: 'Pughanan' },
  { value: 'Pungsod', label: 'Pungsod' },
  { value: 'Quiling', label: 'Quiling' },
  { value: 'Sagcup', label: 'Sagcup' },
  { value: 'San Gregorio', label: 'San Gregorio' },
  { value: 'Sibacungan', label: 'Sibacungan' },
  { value: 'Sibaguan', label: 'Sibaguan' },
  { value: 'Simsiman', label: 'Simsiman' },
  { value: 'Supoc', label: 'Supoc' },
  { value: 'Tampucao', label: 'Tampucao' },
  { value: 'Tranghawan', label: 'Tranghawan' },
  { value: 'Tubungan', label: 'Tubungan' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Walang', label: 'Walang' },
  { value: 'Guintas', label: 'Guintas' },
  { value: 'Lapayon', label: 'Lapayon' },
  { value: 'M. V. Hechanova (Balagon)', label: 'M. V. Hechanova (Balagon)' },
  { value: 'Nabitasan', label: 'Nabitasan' },
  { value: 'Napnud', label: 'Napnud' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'San Vicente', label: 'San Vicente' },
  { value: 'Dapdapan', label: 'Dapdapan' },
  { value: 'Gerongan', label: 'Gerongan' },
  { value: 'Imbaulan', label: 'Imbaulan' },
  { value: 'Layogbato', label: 'Layogbato' },
  { value: 'Marapal', label: 'Marapal' },
  { value: 'Milan', label: 'Milan' },
  { value: 'Nagsulang', label: 'Nagsulang' },
  { value: 'Nasapahan', label: 'Nasapahan' },
  { value: 'Omio', label: 'Omio' },
  { value: 'Pacuan', label: 'Pacuan' },
  { value: 'Poblacion NW Zone', label: 'Poblacion NW Zone' },
  { value: 'Poblacion SE Zone', label: 'Poblacion SE Zone' },
  { value: 'Pontoc', label: 'Pontoc' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'San Diego', label: 'San Diego' },
  { value: 'San Jose Moto', label: 'San Jose Moto' },
  { value: 'Sepanton', label: 'Sepanton' },
  { value: 'Sincua', label: 'Sincua' },
  { value: 'Tabunan', label: 'Tabunan' },
  { value: 'Tugas', label: 'Tugas' },
  { value: 'Velasco', label: 'Velasco' },
  { value: 'Yawyawan', label: 'Yawyawan' },
  { value: 'Avanzada', label: 'Avanzada' },
  { value: 'Awis', label: 'Awis' },
  { value: 'Ayabang', label: 'Ayabang' },
  { value: 'Ayubo', label: 'Ayubo' },
  { value: 'Bacolod', label: 'Bacolod' },
  { value: 'Baje', label: 'Baje' },
  { value: 'Banagan', label: 'Banagan' },
  { value: 'Barangbang', label: 'Barangbang' },
  { value: 'Barasan', label: 'Barasan' },
  { value: 'Bayag Norte', label: 'Bayag Norte' },
  { value: 'Bayag Sur', label: 'Bayag Sur' },
  { value: 'Binolbog', label: 'Binolbog' },
  { value: 'Biri Norte', label: 'Biri Norte' },
  { value: 'Biri Sur', label: 'Biri Sur' },
  { value: 'Bobon', label: 'Bobon' },
  { value: 'Bucari', label: 'Bucari' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Buga', label: 'Buga' },
  { value: 'Bulad', label: 'Bulad' },
  { value: 'Bulwang', label: 'Bulwang' },
  { value: 'Cabolo-an', label: 'Cabolo-an' },
  { value: 'Cabunga-an', label: 'Cabunga-an' },
  { value: 'Cabutongan', label: 'Cabutongan' },
  { value: 'Cagay', label: 'Cagay' },
  { value: 'Camandag', label: 'Camandag' },
  { value: 'Camando', label: 'Camando' },
  { value: 'Cananaman', label: 'Cananaman' },
  { value: 'Capt. Fernando', label: 'Capt. Fernando' },
  { value: 'Carara-an', label: 'Carara-an' },
  { value: 'Carolina', label: 'Carolina' },
  { value: 'Cawilihan', label: 'Cawilihan' },
  { value: 'Coyugan Norte', label: 'Coyugan Norte' },
  { value: 'Coyugan Sur', label: 'Coyugan Sur' },
  { value: 'Danao', label: 'Danao' },
  { value: 'Dorog', label: 'Dorog' },
  { value: 'Dusacan', label: 'Dusacan' },
  { value: 'Gines', label: 'Gines' },
  { value: 'Gumboc', label: 'Gumboc' },
  { value: 'Igcadios', label: 'Igcadios' },
  { value: 'Ingay', label: 'Ingay' },
  { value: 'Isian Norte', label: 'Isian Norte' },
  { value: 'Isian Victoria', label: 'Isian Victoria' },
  { value: 'Jamog Gines', label: 'Jamog Gines' },
  { value: 'Lampaya', label: 'Lampaya' },
  { value: 'Lanag', label: 'Lanag' },
  { value: 'Lang-og', label: 'Lang-og' },
  { value: 'Ligtos', label: 'Ligtos' },
  { value: 'Lonoc', label: 'Lonoc' },
  { value: 'Magcapay', label: 'Magcapay' },
  { value: 'Maliao', label: 'Maliao' },
  { value: 'Malublub', label: 'Malublub' },
  { value: 'Manampunay', label: 'Manampunay' },
  { value: 'Marirong', label: 'Marirong' },
  { value: 'Mina', label: 'Mina' },
  { value: 'Mocol', label: 'Mocol' },
  { value: 'Nagbangi', label: 'Nagbangi' },
  { value: 'Nalbang', label: 'Nalbang' },
  { value: 'Odong-odong', label: 'Odong-odong' },
  { value: 'Oluangan', label: 'Oluangan' },
  { value: 'Omambong', label: 'Omambong' },
  { value: 'Paga', label: 'Paga' },
  { value: 'Pandan', label: 'Pandan' },
  { value: 'Panginman', label: 'Panginman' },
  { value: 'Paoy', label: 'Paoy' },
  { value: 'Pepe', label: 'Pepe' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Salngan', label: 'Salngan' },
  { value: 'Samlague', label: 'Samlague' },
  { value: 'Siol Norte', label: 'Siol Norte' },
  { value: 'Siol Sur', label: 'Siol Sur' },
  { value: 'Tacuyong Norte', label: 'Tacuyong Norte' },
  { value: 'Tacuyong Sur', label: 'Tacuyong Sur' },
  { value: 'Tagsing', label: 'Tagsing' },
  { value: 'Talacuan', label: 'Talacuan' },
  { value: 'Ticuan', label: 'Ticuan' },
  { value: 'Tina-an Norte', label: 'Tina-an Norte' },
  { value: 'Tina-an Sur', label: 'Tina-an Sur' },
  { value: 'Tunguan', label: 'Tunguan' },
  { value: 'Tu-og', label: 'Tu-og' },
  { value: 'Burak', label: 'Burak' },
  { value: 'Cabangcalan', label: 'Cabangcalan' },
  { value: 'Cabatac', label: 'Cabatac' },
  { value: 'Caigon', label: 'Caigon' },
  { value: 'Cananghan', label: 'Cananghan' },
  { value: 'Canawili', label: 'Canawili' },
  { value: 'Dagami', label: 'Dagami' },
  { value: 'Daja', label: 'Daja' },
  { value: 'Dalusan', label: 'Dalusan' },
  {
    value: 'DELCAR Poblacion (Delgado-Cartagena)',
    label: 'DELCAR Poblacion (Delgado-Cartagena)',
  },
  { value: 'Inabasan', label: 'Inabasan' },
  { value: 'Layog', label: 'Layog' },
  { value: 'Linab', label: 'Linab' },
  { value: 'Li-agan Calsada', label: 'Li-agan Calsada' },
  { value: 'Li-agan Tacas', label: 'Li-agan Tacas' },
  { value: 'Magsaysay', label: 'Magsaysay' },
  { value: 'Mandog', label: 'Mandog' },
  {
    value: 'MARI Poblacion (Mabini-Rizal)',
    label: 'MARI Poblacion (Mabini-Rizal)',
  },
  { value: 'Miapa', label: 'Miapa' },
  { value: 'Nagba', label: 'Nagba' },
  { value: 'Nasaka', label: 'Nasaka' },
  { value: 'Naslo-Bucao', label: 'Naslo-Bucao' },
  { value: 'Nasuli', label: 'Nasuli' },
  { value: 'Panalian', label: 'Panalian' },
  { value: 'Piandaan East', label: 'Piandaan East' },
  { value: 'Piandaan West', label: 'Piandaan West' },
  { value: 'Pispis', label: 'Pispis' },
  { value: 'Punong', label: 'Punong' },
  { value: 'Santa Rita', label: 'Santa Rita' },
  { value: 'Sinubsuban', label: 'Sinubsuban' },
  { value: 'Siwalo', label: 'Siwalo' },
  { value: 'Subog', label: 'Subog' },
  {
    value: 'THTP Poblacion (Taft-Thompson-Hughes-del Pilar)',
    label: 'THTP Poblacion (Taft-Thompson-Hughes-del Pilar)',
  },
  { value: 'Tigbauan', label: 'Tigbauan' },
  { value: 'Trangka', label: 'Trangka' },
  { value: 'Tubang', label: 'Tubang' },
  { value: 'Tulahong', label: 'Tulahong' },
  { value: 'Tuy-an East', label: 'Tuy-an East' },
  { value: 'Tuy-an West', label: 'Tuy-an West' },
  { value: 'Ubian', label: 'Ubian' },
  { value: 'Bacauan', label: 'Bacauan' },
  { value: 'Bacolod', label: 'Bacolod' },
  { value: 'Bagumbayan', label: 'Bagumbayan' },
  { value: 'Banbanan', label: 'Banbanan' },
  { value: 'Banga', label: 'Banga' },
  { value: 'Bangladan', label: 'Bangladan' },
  { value: 'Banuyao', label: 'Banuyao' },
  { value: 'Baraclayan', label: 'Baraclayan' },
  { value: 'Bariri', label: 'Bariri' },
  { value: 'Baybay Norte (Poblacion)', label: 'Baybay Norte (Poblacion)' },
  { value: 'Baybay Sur (Poblacion)', label: 'Baybay Sur (Poblacion)' },
  { value: 'Belen', label: 'Belen' },
  { value: 'Bolho (Poblacion)', label: 'Bolho (Poblacion)' },
  { value: 'Bolocaue', label: 'Bolocaue' },
  { value: 'Buenavista Norte', label: 'Buenavista Norte' },
  { value: 'Buenavista Sur', label: 'Buenavista Sur' },
  { value: 'Bugtong Lumangan', label: 'Bugtong Lumangan' },
  { value: 'Bugtong Naulid', label: 'Bugtong Naulid' },
  { value: 'Cabalaunan', label: 'Cabalaunan' },
  { value: 'Cabangcalan', label: 'Cabangcalan' },
  { value: 'Cabunotan', label: 'Cabunotan' },
  { value: 'Cadoldolan', label: 'Cadoldolan' },
  { value: 'Cagbang', label: 'Cagbang' },
  { value: 'Caitib', label: 'Caitib' },
  { value: 'Calagtangan', label: 'Calagtangan' },
  { value: 'Calampitao', label: 'Calampitao' },
  { value: 'Cavite', label: 'Cavite' },
  { value: 'Cawayanan', label: 'Cawayanan' },
  { value: 'Cubay', label: 'Cubay' },
  { value: 'Cubay Ubos', label: 'Cubay Ubos' },
  { value: 'Dalije', label: 'Dalije' },
  { value: 'Damilisan', label: 'Damilisan' },
  { value: 'Dawog', label: 'Dawog' },
  { value: 'Diday', label: 'Diday' },
  { value: 'Dingle', label: 'Dingle' },
  { value: 'Durog', label: 'Durog' },
  { value: 'Frantilla', label: 'Frantilla' },
  { value: 'Fundacion', label: 'Fundacion' },
  { value: 'Gines', label: 'Gines' },
  { value: 'Guibongan', label: 'Guibongan' },
  { value: 'Igbita', label: 'Igbita' },
  { value: 'Igbugo', label: 'Igbugo' },
  { value: 'Igcabidio', label: 'Igcabidio' },
  { value: 'Igcabito-on', label: 'Igcabito-on' },
  { value: 'Igcatambor', label: 'Igcatambor' },
  { value: 'Igdalaquit', label: 'Igdalaquit' },
  { value: 'Igdulaca', label: 'Igdulaca' },
  { value: 'Igpajo', label: 'Igpajo' },
  { value: 'Igpandan', label: 'Igpandan' },
  { value: 'Igpuro', label: 'Igpuro' },
  { value: 'Igpuro-Bariri', label: 'Igpuro-Bariri' },
  { value: 'Igsoligue', label: 'Igsoligue' },
  { value: 'Igtuba', label: 'Igtuba' },
  { value: 'Ilog-ilog', label: 'Ilog-ilog' },
  { value: 'Indag-an', label: 'Indag-an' },
  { value: 'Kirayan Norte', label: 'Kirayan Norte' },
  { value: 'Kirayan Sur', label: 'Kirayan Sur' },
  { value: 'Kirayan Tacas', label: 'Kirayan Tacas' },
  { value: 'La Consolacion', label: 'La Consolacion' },
  { value: 'Lacadon', label: 'Lacadon' },
  { value: 'Lanutan', label: 'Lanutan' },
  { value: 'Lumangan', label: 'Lumangan' },
  { value: 'Mabayan', label: 'Mabayan' },
  { value: 'Maduyo', label: 'Maduyo' },
  { value: 'Malagyan', label: 'Malagyan' },
  { value: 'Mambatad', label: 'Mambatad' },
  { value: 'Maninila', label: 'Maninila' },
  { value: 'Maricolcol', label: 'Maricolcol' },
  { value: 'Maringyan', label: 'Maringyan' },
  { value: 'Matalngon', label: 'Matalngon' },
  { value: 'Mat-y (Poblacion)', label: 'Mat-y (Poblacion)' },
  { value: 'Naclub', label: 'Naclub' },
  { value: 'Nam-o Norte', label: 'Nam-o Norte' },
  { value: 'Nam-o Sur', label: 'Nam-o Sur' },
  { value: 'Narat-an', label: 'Narat-an' },
  { value: 'Narorogan', label: 'Narorogan' },
  { value: 'Naulid', label: 'Naulid' },
  { value: 'Olango', label: 'Olango' },
  { value: 'Ongyod', label: 'Ongyod' },
  { value: 'Onop', label: 'Onop' },
  { value: 'Oya-oy', label: 'Oya-oy' },
  { value: 'Oyungan', label: 'Oyungan' },
  { value: 'Palaca', label: 'Palaca' },
  { value: 'Paro-on', label: 'Paro-on' },
  { value: 'Potrido', label: 'Potrido' },
  { value: 'Pudpud', label: 'Pudpud' },
  { value: 'Pungtod Monteclaro', label: 'Pungtod Monteclaro' },
  { value: 'Pungtod Naulid', label: 'Pungtod Naulid' },
  { value: 'Sag-on', label: 'Sag-on' },
  { value: 'San Fernando', label: 'San Fernando' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'San Rafael', label: 'San Rafael' },
  { value: 'Sapa (Miagao)', label: 'Sapa (Miagao)' },
  { value: 'Saring', label: 'Saring' },
  { value: 'Sibucao', label: 'Sibucao' },
  { value: 'Taal', label: 'Taal' },
  { value: 'Tabunacan', label: 'Tabunacan' },
  { value: 'Tacas (Poblacion)', label: 'Tacas (Poblacion)' },
  { value: 'Tambong', label: 'Tambong' },
  { value: 'Tan-agan', label: 'Tan-agan' },
  { value: 'Tatoy', label: 'Tatoy' },
  { value: 'Ticdalan', label: 'Ticdalan' },
  { value: 'Tig-amaga', label: 'Tig-amaga' },
  { value: 'Tig-Apog-Apog', label: 'Tig-Apog-Apog' },
  { value: 'Tigbagacay', label: 'Tigbagacay' },
  { value: 'Tiglawa', label: 'Tiglawa' },
  { value: 'Tigmalapad', label: 'Tigmalapad' },
  { value: 'Tigmarabo', label: 'Tigmarabo' },
  { value: 'To-og', label: 'To-og' },
  { value: 'Tugura-ao', label: 'Tugura-ao' },
  { value: 'Tumagboc', label: 'Tumagboc' },
  { value: 'Ubos Ilawod (Poblacion)', label: 'Ubos Ilawod (Poblacion)' },
  { value: 'Ubos Ilaya (Poblacion)', label: 'Ubos Ilaya (Poblacion)' },
  { value: 'Valencia', label: 'Valencia' },
  { value: 'Wayang', label: 'Wayang' },
  { value: 'Badiangan', label: 'Badiangan' },
  { value: 'Bangac', label: 'Bangac' },
  { value: 'Cabalabaguan', label: 'Cabalabaguan' },
  { value: 'Capul-an', label: 'Capul-an' },
  { value: 'Dala', label: 'Dala' },
  { value: 'Guibuangan', label: 'Guibuangan' },
  { value: 'Janipa-an East', label: 'Janipa-an East' },
  { value: 'Janipa-an West', label: 'Janipa-an West' },
  { value: 'Mina East (Poblacion)', label: 'Mina East (Poblacion)' },
  { value: 'Mina West (Poblacion)', label: 'Mina West (Poblacion)' },
  { value: 'Nasirum', label: 'Nasirum' },
  { value: 'Naumuan', label: 'Naumuan' },
  { value: 'Singay', label: 'Singay' },
  { value: 'Talibong Grande', label: 'Talibong Grande' },
  { value: 'Talibong Pequeño', label: 'Talibong Pequeño' },
  { value: 'Tipolo', label: 'Tipolo' },
  { value: 'Tolarucan', label: 'Tolarucan' },
  { value: 'Tumay', label: 'Tumay' },
  { value: 'Yugot', label: 'Yugot' },
  { value: 'Bita?og Gaja', label: 'Bita?og Gaja' },
  { value: 'Bololacao', label: 'Bololacao' },
  { value: 'Burot', label: 'Burot' },
  { value: 'Cabilauan', label: 'Cabilauan' },
  { value: 'Cabugao', label: 'Cabugao' },
  { value: 'Cagban', label: 'Cagban' },
  { value: 'Calumbuyan', label: 'Calumbuyan' },
  { value: 'Damires', label: 'Damires' },
  { value: 'Dawis', label: 'Dawis' },
  { value: 'General Delgado', label: 'General Delgado' },
  { value: 'Guinobatan', label: 'Guinobatan' },
  { value: 'Janipa-an Oeste', label: 'Janipa-an Oeste' },
  { value: 'Jelicuon Este', label: 'Jelicuon Este' },
  { value: 'Jelicuon Oeste', label: 'Jelicuon Oeste' },
  { value: 'Pasil', label: 'Pasil' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'Wari-wari', label: 'Wari-wari' },
  { value: 'Bita Sur', label: 'Bita Sur' },
  { value: 'Botong', label: 'Botong' },
  { value: 'Buray', label: 'Buray' },
  { value: 'Cabanbanan', label: 'Cabanbanan' },
  { value: 'Caboloan Norte', label: 'Caboloan Norte' },
  { value: 'Caboloan Sur', label: 'Caboloan Sur' },
  { value: 'Cadinglian', label: 'Cadinglian' },
  { value: 'Cagbang', label: 'Cagbang' },
  { value: 'Calam-isan', label: 'Calam-isan' },
  { value: 'Galang', label: 'Galang' },
  { value: 'Lambuyao', label: 'Lambuyao' },
  { value: 'Mambog', label: 'Mambog' },
  { value: 'Pakiad', label: 'Pakiad' },
  { value: 'Poblacion East', label: 'Poblacion East' },
  { value: 'Poblacion North', label: 'Poblacion North' },
  { value: 'Poblacion South', label: 'Poblacion South' },
  { value: 'Poblacion West', label: 'Poblacion West' },
  { value: 'Polo Maestra Bita', label: 'Polo Maestra Bita' },
  { value: 'Rizal', label: 'Rizal' },
  { value: 'Salngan', label: 'Salngan' },
  { value: 'Sambaludan', label: 'Sambaludan' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'San Nicolas', label: 'San Nicolas' },
  { value: 'Santa Clara', label: 'Santa Clara' },
  { value: 'Santa Monica', label: 'Santa Monica' },
  { value: 'Santa Rita', label: 'Santa Rita' },
  { value: 'Tagbac Norte', label: 'Tagbac Norte' },
  { value: 'Tagbac Sur', label: 'Tagbac Sur' },
  { value: 'Trapiche', label: 'Trapiche' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Turog Turog', label: 'Turog Turog' },
  { value: 'Alimono', label: 'Alimono' },
  { value: 'Arac', label: 'Arac' },
  { value: 'Ayuyan', label: 'Ayuyan' },
  { value: 'Bacuranan', label: 'Bacuranan' },
  { value: 'Bagacay', label: 'Bagacay' },
  { value: 'Batu', label: 'Batu' },
  { value: 'Bayan', label: 'Bayan' },
  { value: 'Bitaogan', label: 'Bitaogan' },
  { value: 'Buenavista', label: 'Buenavista' },
  { value: 'Buyo', label: 'Buyo' },
  { value: 'Cabunga', label: 'Cabunga' },
  { value: 'Cadilang', label: 'Cadilang' },
  { value: 'Cairohan', label: 'Cairohan' },
  { value: 'Dalicanan', label: 'Dalicanan' },
  { value: 'Gegachac', label: 'Gegachac' },
  { value: 'Gemat-y', label: 'Gemat-y' },
  { value: 'Gemumua-agahon', label: 'Gemumua-agahon' },
  { value: 'Gines Viejo', label: 'Gines Viejo' },
  { value: 'Imbang Grande', label: 'Imbang Grande' },
  { value: 'Jaguimitan', label: 'Jaguimitan' },
  { value: 'Libo-o', label: 'Libo-o' },
  { value: 'Maasin', label: 'Maasin' },
  { value: 'Magdungao', label: 'Magdungao' },
  { value: 'Malag-it Grande', label: 'Malag-it Grande' },
  { value: 'Malag-it Pequeño', label: 'Malag-it Pequeño' },
  { value: 'Mambiranan Grande', label: 'Mambiranan Grande' },
  { value: 'Mambiranan Pequeño', label: 'Mambiranan Pequeño' },
  { value: 'Man-it', label: 'Man-it' },
  { value: 'Mantulang', label: 'Mantulang' },
  { value: 'Mulapula', label: 'Mulapula' },
  { value: 'Nueva Union', label: 'Nueva Union' },
  { value: 'Pagaypay', label: 'Pagaypay' },
  { value: 'Pangi', label: 'Pangi' },
  { value: 'Poblacion Ilawod', label: 'Poblacion Ilawod' },
  { value: 'Poblacion Ilaya', label: 'Poblacion Ilaya' },
  { value: 'Punong', label: 'Punong' },
  { value: 'Quinagaringan Grande', label: 'Quinagaringan Grande' },
  { value: 'Quinagaringan Pequeño', label: 'Quinagaringan Pequeño' },
  { value: 'Sablogon', label: 'Sablogon' },
  { value: 'Salngan', label: 'Salngan' },
  { value: 'Santo Tomas', label: 'Santo Tomas' },
  { value: 'Sarapan', label: 'Sarapan' },
  { value: 'Tagubong', label: 'Tagubong' },
  { value: 'Talongonan', label: 'Talongonan' },
  { value: 'Tubod', label: 'Tubod' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Pagsanga?an', label: 'Pagsanga?an' },
  { value: 'Pal?agon', label: 'Pal?agon' },
  { value: 'Pandac', label: 'Pandac' },
  { value: 'Purok I (Poblacion)', label: 'Purok I (Poblacion)' },
  { value: 'Purok II (Poblacion)', label: 'Purok II (Poblacion)' },
  { value: 'Purok III (Poblacion)', label: 'Purok III (Poblacion)' },
  { value: 'Purok IV (Poblacion)', label: 'Purok IV (Poblacion)' },
  { value: 'Tigum', label: 'Tigum' },
  { value: 'Ungka I', label: 'Ungka I' },
  { value: 'Ungka II', label: 'Ungka II' },
  { value: 'Cahaguichican', label: 'Cahaguichican' },
  { value: 'Callan', label: 'Callan' },
  { value: 'Cansilayan', label: 'Cansilayan' },
  { value: 'Casalsagan', label: 'Casalsagan' },
  { value: 'Cato-ogan', label: 'Cato-ogan' },
  { value: 'Cau-ayan', label: 'Cau-ayan' },
  { value: 'Culob', label: 'Culob' },
  { value: 'Danao', label: 'Danao' },
  { value: 'Dapitan', label: 'Dapitan' },
  { value: 'Dawis', label: 'Dawis' },
  { value: 'Dongsol', label: 'Dongsol' },
  {
    value: 'Fernando Parcon Ward (Poblacion)',
    label: 'Fernando Parcon Ward (Poblacion)',
  },
  { value: 'Fundacion', label: 'Fundacion' },
  { value: 'Guibuangan', label: 'Guibuangan' },
  { value: 'Guinacas', label: 'Guinacas' },
  { value: 'Igang', label: 'Igang' },
  { value: 'Intaluan', label: 'Intaluan' },
  { value: 'Iwa Ilaud', label: 'Iwa Ilaud' },
  { value: 'Iwa Ilaya', label: 'Iwa Ilaya' },
  { value: 'Jamabalud', label: 'Jamabalud' },
  { value: 'Jebioc', label: 'Jebioc' },
  { value: 'Lay-Ahan', label: 'Lay-Ahan' },
  {
    value: 'Lopez Jaena Ward (Poblacion)',
    label: 'Lopez Jaena Ward (Poblacion)',
  },
  { value: 'Lumbo', label: 'Lumbo' },
  { value: 'Macatol', label: 'Macatol' },
  { value: 'Malusgod', label: 'Malusgod' },
  { value: 'Nabitasan', label: 'Nabitasan' },
  { value: 'Naga', label: 'Naga' },
  { value: 'Nanga', label: 'Nanga' },
  { value: 'Naslo', label: 'Naslo' },
  { value: 'Pajo', label: 'Pajo' },
  { value: 'Palanguia', label: 'Palanguia' },
  { value: 'Pitogo', label: 'Pitogo' },
  { value: 'Polot-an', label: 'Polot-an' },
  {
    value: 'Primitivo Ledesma Ward (Poblacion)',
    label: 'Primitivo Ledesma Ward (Poblacion)',
  },
  { value: 'Purog', label: 'Purog' },
  { value: 'Rumbang', label: 'Rumbang' },
  { value: 'San Jose Ward (Poblacion)', label: 'San Jose Ward (Poblacion)' },
  { value: 'Sinuagan', label: 'Sinuagan' },
  { value: 'Tuburan', label: 'Tuburan' },
  { value: 'Tumcon Ilaud', label: 'Tumcon Ilaud' },
  { value: 'Tumcon Ilaya', label: 'Tumcon Ilaya' },
  { value: 'Ubang', label: 'Ubang' },
  { value: 'Zarrague', label: 'Zarrague' },
  { value: 'Cudionan', label: 'Cudionan' },
  { value: 'Dugman', label: 'Dugman' },
  { value: 'Hacienda Conchita', label: 'Hacienda Conchita' },
  { value: 'Madanlog', label: 'Madanlog' },
  { value: 'Mandu-awak', label: 'Mandu-awak' },
  { value: 'Moto', label: 'Moto' },
  { value: 'Naborot', label: 'Naborot' },
  { value: 'Nipa', label: 'Nipa' },
  { value: 'Odiongan', label: 'Odiongan' },
  { value: 'Pangi', label: 'Pangi' },
  { value: 'Pase', label: 'Pase' },
  { value: 'Poblacion', label: 'Poblacion' },
  { value: 'San Nicolas', label: 'San Nicolas' },
  { value: 'Santol', label: 'Santol' },
  { value: 'Siempreviva', label: 'Siempreviva' },
  { value: 'Sua', label: 'Sua' },
  { value: 'Talo-ato', label: 'Talo-ato' },
  { value: 'Tamangi', label: 'Tamangi' },
  { value: 'Tiabas', label: 'Tiabas' },
  { value: 'Tuble', label: 'Tuble' },
  { value: 'Dacal', label: 'Dacal' },
  { value: 'Dumiles', label: 'Dumiles' },
  { value: 'Garita', label: 'Garita' },
  { value: 'Gines Nuevo', label: 'Gines Nuevo' },
  { value: 'Imbang Pequeño', label: 'Imbang Pequeño' },
  { value: 'Imbesad-an', label: 'Imbesad-an' },
  { value: 'Iprog', label: 'Iprog' },
  { value: 'Lip-ac', label: 'Lip-ac' },
  { value: 'Madarag', label: 'Madarag' },
  { value: 'Mapili', label: 'Mapili' },
  { value: 'Paga', label: 'Paga' },
  { value: 'Palje', label: 'Palje' },
  { value: 'Poblacion Ilawod', label: 'Poblacion Ilawod' },
  { value: 'Poblacion Ilaya', label: 'Poblacion Ilaya' },
  { value: 'Quinolpan', label: 'Quinolpan' },
  { value: 'Rumagayray', label: 'Rumagayray' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'Tambunac', label: 'Tambunac' },
  { value: 'Bayunan (Panday Oro)', label: 'Bayunan (Panday Oro)' },
  { value: 'Bolbogan', label: 'Bolbogan' },
  { value: 'Bonga', label: 'Bonga' },
  { value: 'Bucaya', label: 'Bucaya' },
  { value: 'Bulho', label: 'Bulho' },
  { value: 'Cadluman', label: 'Cadluman' },
  { value: 'Cadoldolan', label: 'Cadoldolan' },
  { value: 'Camaba-an', label: 'Camaba-an' },
  { value: 'Camia', label: 'Camia' },
  { value: 'Cata-an', label: 'Cata-an' },
  { value: 'Crossing Dapuyan', label: 'Crossing Dapuyan' },
  { value: 'Cubay', label: 'Cubay' },
  { value: 'Cumarascas', label: 'Cumarascas' },
  { value: 'Dacdacanan', label: 'Dacdacanan' },
  { value: 'Danawan', label: 'Danawan' },
  { value: 'Doldol', label: 'Doldol' },
  { value: 'Dongoc', label: 'Dongoc' },
  { value: 'Escalantera', label: 'Escalantera' },
  { value: 'Ginot-an', label: 'Ginot-an' },
  { value: 'Guibongan Bayunan', label: 'Guibongan Bayunan' },
  { value: 'Huna', label: 'Huna' },
  { value: 'Igbaje', label: 'Igbaje' },
  { value: 'Igbangcal', label: 'Igbangcal' },
  { value: 'Igbinangon', label: 'Igbinangon' },
  { value: 'Igburi', label: 'Igburi' },
  { value: 'Igcabutong', label: 'Igcabutong' },
  { value: 'Igcadlum', label: 'Igcadlum' },
  { value: 'Igcaphang', label: 'Igcaphang' },
  { value: 'Igcaratong', label: 'Igcaratong' },
  { value: 'Igcondao', label: 'Igcondao' },
  { value: 'Igcores', label: 'Igcores' },
  { value: 'Igdagmay', label: 'Igdagmay' },
  { value: 'Igdomingding', label: 'Igdomingding' },
  { value: 'Iglilico', label: 'Iglilico' },
  { value: 'Igpayong', label: 'Igpayong' },
  { value: 'Jawod', label: 'Jawod' },
  { value: 'Langca', label: 'Langca' },
  { value: 'Languanan', label: 'Languanan' },
  { value: 'Lawigan', label: 'Lawigan' },
  { value: 'Lomboy', label: 'Lomboy' },
  { value: 'Lomboyan (Santa Ana)', label: 'Lomboyan (Santa Ana)' },
  { value: 'Lopez Vito', label: 'Lopez Vito' },
  { value: 'Mabini Norte', label: 'Mabini Norte' },
  { value: 'Mabini Sur', label: 'Mabini Sur' },
  { value: 'Manhara', label: 'Manhara' },
  { value: 'Maninila', label: 'Maninila' },
  { value: 'Masagud', label: 'Masagud' },
  { value: 'Matambog', label: 'Matambog' },
  { value: 'Mayunoc', label: 'Mayunoc' },
  { value: 'Montinola', label: 'Montinola' },
  { value: 'Nadsadan', label: 'Nadsadan' },
  { value: 'Nagquirisan', label: 'Nagquirisan' },
  { value: 'Nagsipit', label: 'Nagsipit' },
  { value: 'New Gumawan', label: 'New Gumawan' },
  { value: 'Panatan', label: 'Panatan' },
  { value: 'Pitogo', label: 'Pitogo' },
  { value: 'Purok 1 (Poblacion)', label: 'Purok 1 (Poblacion)' },
  { value: 'Purok 2 (Poblacion)', label: 'Purok 2 (Poblacion)' },
  { value: 'Purok 3 (Poblacion)', label: 'Purok 3 (Poblacion)' },
  { value: 'Purok 4 (Poblacion)', label: 'Purok 4 (Poblacion)' },
  { value: 'Purok 5 (Poblacion)', label: 'Purok 5 (Poblacion)' },
  { value: 'Quiñanan', label: 'Quiñanan' },
  { value: 'Roma', label: 'Roma' },
  { value: 'San Luis', label: 'San Luis' },
  { value: 'San Mateo Norte', label: 'San Mateo Norte' },
  { value: 'San Mateo Sur', label: 'San Mateo Sur' },
  { value: 'Santa Rita', label: 'Santa Rita' },
  { value: 'Santiago', label: 'Santiago' },
  { value: 'Sinogbuhan', label: 'Sinogbuhan' },
  { value: 'Siwaragan', label: 'Siwaragan' },
  { value: 'Talagutac', label: 'Talagutac' },
  { value: 'Tapikan', label: 'Tapikan' },
  { value: 'Taslan', label: 'Taslan' },
  { value: 'Tiglawa', label: 'Tiglawa' },
  { value: 'Tiolas', label: 'Tiolas' },
  { value: 'To-og', label: 'To-og' },
  { value: 'Torocadan', label: 'Torocadan' },
  { value: 'Ulay', label: 'Ulay' },
  {
    value: 'Barangay 1 Poblacion (Roxas St.)',
    label: 'Barangay 1 Poblacion (Roxas St.)',
  },
  {
    value: 'Barangay 10 (Poblacion R. V. Sanchez St. South)',
    label: 'Barangay 10 (Poblacion R. V. Sanchez St. South)',
  },
  {
    value: 'Barangay 11 Poblacion (R. V. Sanchez St. North)',
    label: 'Barangay 11 Poblacion (R. V. Sanchez St. North)',
  },
  {
    value: 'Barangay 12 Poblacion (Sales Malaga Saliedo)',
    label: 'Barangay 12 Poblacion (Sales Malaga Saliedo)',
  },
  {
    value: 'Barangay 13 Poblacion (Santa Rita-Saclauso St.)',
    label: 'Barangay 13 Poblacion (Santa Rita-Saclauso St.)',
  },
  {
    value: 'Barangay 14 Poblacion (San Miguel North)',
    label: 'Barangay 14 Poblacion (San Miguel North)',
  },
  {
    value: 'Barangay 15 Poblacion (San Miguel South)',
    label: 'Barangay 15 Poblacion (San Miguel South)',
  },
  {
    value: 'Barangay 16 Poblacion (San Agustin St.)',
    label: 'Barangay 16 Poblacion (San Agustin St.)',
  },
  {
    value: 'Barangay 2 Poblacion (Savilla Santo Rosario)',
    label: 'Barangay 2 Poblacion (Savilla Santo Rosario)',
  },
  {
    value: 'Barangay 3 Poblacion (A. S. Suarez St. Zone 1)',
    label: 'Barangay 3 Poblacion (A. S. Suarez St. Zone 1)',
  },
  {
    value: 'Barangay 4 Poblacion (A. S. Suarez East)',
    label: 'Barangay 4 Poblacion (A. S. Suarez East)',
  },
  {
    value: 'Barangay 5 Poblacion (Santiago St. North)',
    label: 'Barangay 5 Poblacion (Santiago St. North)',
  },
  {
    value: 'Barangay 6 Poblacion (Santiago St. South)',
    label: 'Barangay 6 Poblacion (Santiago St. South)',
  },
  {
    value: 'Barangay 7 Poblacion (San Roque St. South)',
    label: 'Barangay 7 Poblacion (San Roque St. South)',
  },
  {
    value: 'Barangay 8 Poblacion (Montano-San Roque)',
    label: 'Barangay 8 Poblacion (Montano-San Roque)',
  },
  {
    value: 'Barangay 9 Poblacion (Salazar San Jose)',
    label: 'Barangay 9 Poblacion (Salazar San Jose)',
  },
  { value: 'Consolacion', label: 'Consolacion' },
  { value: 'Igtambo', label: 'Igtambo' },
  { value: 'San Antonio', label: 'San Antonio' },
  { value: 'San Jose', label: 'San Jose' },
  { value: 'Santa Cruz', label: 'Santa Cruz' },
  { value: 'Santa Teresa', label: 'Santa Teresa' },
  { value: 'Santo Angel', label: 'Santo Angel' },
  { value: 'Santo Nino', label: 'Santo Nino' },
];
export default barangayOptionTypes
