const countriesList = [
  { name: 'N/A' },
  { name: 'Afghanistan' },
  { name: 'Angola' },
  { name: 'Albania' },
  { name: 'United Arab Emirates' },
  { name: 'Argentina' },
  { name: 'Armenia' },
  { name: 'Antarctica' },
  { name: 'French Southern and Antarctic Lands' },
  { name: 'Australia' },
  { name: 'Austria' },
  { name: 'Azerbaijan' },
  { name: 'Burundi' },
  { name: 'Belgium' },
  { name: 'Benin' },
  { name: 'Burkina Faso' },
  { name: 'Bangladesh' },
  { name: 'Bulgaria' },
  { name: 'Bahamas' },
  { name: 'Bosnia and Herzegovina' },
  { name: 'Belarus' },
  { name: 'Belize' },
  { name: 'Bolivia' },
  { name: 'Brazil' },
  { name: 'Brunei Darussalam' },
  { name: 'Bhutan' },
  { name: 'Botswana' },
  { name: 'Central African Republic' },
  { name: 'Canada' },
  { name: 'Switzerland' },
  { name: 'Chile' },
  { name: 'China' },
  { name: "Côte d'Ivoire" },
  { name: 'Cameroon' },
  { name: 'Democratic Republic of the Congo' },
  { name: 'Republic of the Congo' },
  { name: 'Colombia' },
  { name: 'Costa Rica' },
  { name: 'Cuba' },
  { name: 'Northern Cyprus' },
  { name: 'Cyprus' },
  { name: 'Czech Republic' },
  { name: 'Germany' },
  { name: 'Djibouti' },
  { name: 'Denmark' },
  { name: 'Dominican Republic' },
  { name: 'Algeria' },
  { name: 'Ecuador' },
  { name: 'Egypt' },
  { name: 'Eritrea' },
  { name: 'Spain' },
  { name: 'Estonia' },
  { name: 'Ethiopia' },
  { name: 'Finland' },
  { name: 'Fiji' },
  { name: 'Falkland Islands' },
  { name: 'France' },
  { name: 'Gabon' },
  { name: 'United Kingdom' },
  { name: 'Georgia' },
  { name: 'Ghana' },
  { name: 'Guinea' },
  { name: 'The Gambia' },
  { name: 'Guinea-Bissau' },
  { name: 'Equatorial Guinea' },
  { name: 'Greece' },
  { name: 'Greenland' },
  { name: 'Guatemala' },
  { name: 'Guyana' },
  { name: 'Honduras' },
  { name: 'Croatia' },
  { name: 'Haiti' },
  { name: 'Hungary' },
  { name: 'Indonesia' },
  { name: 'India' },
  { name: 'Ireland' },
  { name: 'Iran' },
  { name: 'Iraq' },
  { name: 'Iceland' },
  { name: 'Israel' },
  { name: 'Italy' },
  { name: 'Jamaica' },
  { name: 'Jordan' },
  { name: 'Japan' },
  { name: 'Kazakhstan' },
  { name: 'Kenya' },
  { name: 'Kyrgyzstan' },
  { name: 'Cambodia' },
  { name: 'Republic of Korea' },
  { name: 'Kosovo' },
  { name: 'Kuwait' },
  { name: 'Lao PDR' },
  { name: 'Lebanon' },
  { name: 'Liberia' },
  { name: 'Libya' },
  { name: 'Sri Lanka' },
  { name: 'Lesotho' },
  { name: 'Lithuania' },
  { name: 'Luxembourg' },
  { name: 'Latvia' },
  { name: 'Morocco' },
  { name: 'Moldova' },
  { name: 'Madagascar' },
  { name: 'Mexico' },
  { name: 'Macedonia' },
  { name: 'Mali' },
  { name: 'Myanmar' },
  { name: 'Montenegro' },
  { name: 'Mongolia' },
  { name: 'Mozambique' },
  { name: 'Mauritania' },
  { name: 'Malawi' },
  { name: 'Malaysia' },
  { name: 'Namibia' },
  { name: 'New Caledonia' },
  { name: 'Niger' },
  { name: 'Nigeria' },
  { name: 'Nicaragua' },
  { name: 'Netherlands' },
  { name: 'Norway' },
  { name: 'Nepal' },
  { name: 'New Zealand' },
  { name: 'Oman' },
  { name: 'Pakistan' },
  { name: 'Panama' },
  { name: 'Peru' },
  { name: 'Philippines' },
  { name: 'Papua New Guinea' },
  { name: 'Poland' },
  { name: 'Puerto Rico' },
  { name: 'Dem. Rep. Korea' },
  { name: 'Portugal' },
  { name: 'Paraguay' },
  { name: 'Palestine' },
  { name: 'Qatar' },
  { name: 'Romania' },
  { name: 'Russian Federation' },
  { name: 'Rwanda' },
  { name: 'Western Sahara' },
  { name: 'Saudi Arabia' },
  { name: 'Sudan' },
  { name: 'South Sudan' },
  { name: 'Senegal' },
  { name: 'Solomon Islands' },
  { name: 'Sierra Leone' },
  { name: 'Singapore' },
  { name: 'El Salvador' },
  { name: 'Somaliland' },
  { name: 'Somalia' },
  { name: 'Serbia' },
  { name: 'Suriname' },
  { name: 'Slovakia' },
  { name: 'Slovenia' },
  { name: 'Sweden' },
  { name: 'Swaziland' },
  { name: 'Syria' },
  { name: 'Chad' },
  { name: 'Togo' },
  { name: 'Thailand' },
  { name: 'Tajikistan' },
  { name: 'Turkmenistan' },
  { name: 'Timor-Leste' },
  { name: 'Trinidad and Tobago' },
  { name: 'Tunisia' },
  { name: 'Turkey' },
  { name: 'Taiwan' },
  { name: 'Tanzania' },
  { name: 'Uganda' },
  { name: 'Ukraine' },
  { name: 'Uruguay' },
  { name: 'United States' },
  { name: 'Uzbekistan' },
  { name: 'Venezuela' },
  { name: 'Vietnam' },
  { name: 'Vanuatu' },
  { name: 'Yemen' },
  { name: 'South Africa' },
  { name: 'Zambia' },
  { name: 'Zimbabwe' },
];
export default countriesList
