const jobGroupTypes = [
  { value: '', label: '' },
  { value: 'CLERKS', label: 'CLERKS' },
  {
    value: 'ACCOUNTANTS AND FINANCE STAFF',
    label: 'ACCOUNTANTS AND FINANCE STAFF',
  },
  {
    value: 'OPERATION MANAGERS/SUPERVISOR',
    label: 'OPERATION MANAGERS/SUPERVISOR',
  },
  {
    value: 'CUSTOMER SERVICE REPRESENTATIVE',
    label: 'CUSTOMER SERVICE REPRESENTATIVE',
  },
  { value: 'OFFICE STAFF', label: 'OFFICE STAFF' },
  { value: 'PRODUCTION WORKER', label: 'PRODUCTION WORKER' },
  { value: 'GENERAL SERVICE PERSONNEL', label: 'GENERAL SERVICE PERSONNEL' },
  { value: 'ARCHITECTS', label: 'ARCHITECTS' },
  { value: 'SALES PERSONNEL', label: 'SALES PERSONNEL' },
  { value: 'NURSE', label: 'NURSE' },
  { value: 'DATA SPECIALISTS', label: 'DATA SPECIALISTS' },
  { value: 'ASSOCIATE DESIGN ENGINEER', label: 'ASSOCIATE DESIGN ENGINEER' },
  { value: 'CREATIVE SECTION STAFF', label: 'CREATIVE SECTION STAFF' },
  { value: 'BAKERS AND COOKS', label: 'BAKERS AND COOKS' },
  { value: 'AUDITORS', label: 'AUDITORS' },
  { value: 'ELECTRICIAN', label: 'ELECTRICIAN' },
  { value: 'MECHANIC', label: 'MECHANIC' },
  { value: 'WELDERS', label: 'WELDERS' },
  { value: 'HEAVY EQUIPMENT OPERATORS', label: 'HEAVY EQUIPMENT OPERATORS' },
  { value: 'STORE CREWS', label: 'STORE CREWS' },
  { value: 'TEACHERS', label: 'TEACHERS' },
  { value: 'BARGEMAN', label: 'BARGEMAN' },
  { value: 'BARTENDER', label: 'BARTENDER' },
  { value: 'BEAUTICIAN', label: 'BEAUTICIAN' },
  { value: 'BEAUTY CONSULTANTS', label: 'BEAUTY CONSULTANTS' },
  { value: 'CASHIER', label: 'CASHIER' },
  { value: 'CAREGIVER', label: 'CAREGIVER' },
  { value: 'CONSTRUCTION WORKER', label: 'CONSTRUCTION WORKER' },
  { value: 'CHEMICAL ENGINEER', label: 'CHEMICAL ENGINEER' },
  { value: 'CHEMICAL ENGINEERING', label: 'CHEMICAL ENGINEERING' },
  { value: 'CHEMISTS', label: 'CHEMISTS' },
  { value: 'COMPLIANCE OFFICER', label: 'COMPLIANCE OFFICER' },
  { value: 'CIVIL ENGINEER', label: 'CIVIL ENGINEER' },
  { value: 'CIVIL ENGINEERING', label: 'CIVIL ENGINEERING' },
  {
    value: 'CREDIT AND COLLECTION OFFICERS',
    label: 'CREDIT AND COLLECTION OFFICERS',
  },
  {
    value: 'FINANCIAL/INVESTMENT CONSULTANTS',
    label: 'FINANCIAL/INVESTMENT CONSULTANTS',
  },
  { value: 'DRIVERS', label: 'DRIVERS' },
  { value: 'COMPUTER ENGINEER', label: 'COMPUTER ENGINEER' },
  { value: 'IT SPECIALIST', label: 'IT SPECIALIST' },
  { value: 'FOOD SERVERS', label: 'FOOD SERVERS' },
  { value: 'HEALTHCARE WORKER', label: 'HEALTHCARE WORKER' },
  { value: 'MECHANIC ', label: 'MECHANIC ' },
  { value: 'DOMESTIC HELPER', label: 'DOMESTIC HELPER' },
  { value: 'ELECTRICAL ENGINEER', label: 'ELECTRICAL ENGINEER' },
  { value: 'ELECTRONICS ENGINEERS', label: 'ELECTRONICS ENGINEERS' },
  { value: 'QUALITY ASSURANCE ENGINEER', label: 'QUALITY ASSURANCE ENGINEER' },
  { value: 'EVENTS COORDINATOR', label: 'EVENTS COORDINATOR' },
  { value: 'FASHION DESIGNER', label: 'FASHION DESIGNER' },
  { value: 'PHARMACIST', label: 'PHARMACIST' },
  { value: 'HR PERSONNEL', label: 'HR PERSONNEL' },
  { value: 'SECURITY OFFICERS', label: 'SECURITY OFFICERS' },
  { value: 'LAWYER', label: 'LAWYER' },
  { value: 'MASSAGE THERAPIST', label: 'MASSAGE THERAPIST' },
  { value: 'MECHANICAL ENGINEER', label: 'MECHANICAL ENGINEER' },
  { value: 'MEDICAL TECHNOLOGIST', label: 'MEDICAL TECHNOLOGIST' },
  { value: 'MIDWIFE', label: 'MIDWIFE' },
  { value: 'OUTAGE CONTROL ENGINEER', label: 'OUTAGE CONTROL ENGINEER' },
  { value: 'PARTS SALES ENGINEER', label: 'PARTS SALES ENGINEER' },
  { value: 'PRODUCTION ENGINEER', label: 'PRODUCTION ENGINEER' },
  { value: 'PROJECT ENGINEERS', label: 'PROJECT ENGINEERS' },
  {
    value: 'RESEARCH & DEVELOPMENT SPECIALIST',
    label: 'RESEARCH & DEVELOPMENT SPECIALIST',
  },
  { value: 'SITE ENGINEER', label: 'SITE ENGINEER' },
  { value: 'TAILOR', label: 'TAILOR' },
  {
    value: 'TECHNICAL OPERATIONS ENGINEER',
    label: 'TECHNICAL OPERATIONS ENGINEER',
  },
  { value: 'TREATMENT TECHNICIAN', label: 'TREATMENT TECHNICIAN' },
  {
    value: 'ELECTRONICS AND COMMUNICATION ENGINEER',
    label: 'ELECTRONICS AND COMMUNICATION ENGINEER',
  },
  {
    value: 'ENGINEERING DESIGN ASSISTANT',
    label: 'ENGINEERING DESIGN ASSISTANT',
  },
  {
    value: 'ELECTRONICS AND COMMUNICATION ENGINEERING',
    label: 'ELECTRONICS AND COMMUNICATION ENGINEERING',
  },
];
export default jobGroupTypes