const municipalityTypes = [
  { value: 'AJUY', label: 'AJUY' },
  { value: 'ALIMODIAN', label: 'ALIMODIAN' },
  { value: 'ANILAO', label: 'ANILAO' },
  { value: 'BADIANGAN', label: 'BADIANGAN' },
  { value: 'BALASAN', label: 'BALASAN' },
  { value: 'BANATE', label: 'BANATE' },
  { value: 'BAROTAC NUEVO', label: 'BAROTAC NUEVO' },
  { value: 'BAROTAC VIEJO', label: 'BAROTAC VIEJO' },
  { value: 'BATAD', label: 'BATAD' },
  { value: 'BINGAWAN', label: 'BINGAWAN' },
  { value: 'CABATUAN', label: 'CABATUAN' },
  { value: 'CALINOG', label: 'CALINOG' },
  { value: 'CARLES', label: 'CARLES' },
  { value: 'CONCEPCION', label: 'CONCEPCION' },
  { value: 'DINGLE', label: 'DINGLE' },
  { value: 'DUENAS', label: 'DUENAS' },
  { value: 'DUMANGAS', label: 'DUMANGAS' },
  { value: 'ESTANCIA', label: 'ESTANCIA' },
  { value: 'GUIMBAL', label: 'GUIMBAL' },
  { value: 'IGBARAS', label: 'IGBARAS' },
  { value: 'JANIUAY', label: 'JANIUAY' },
  { value: 'LAMBUNAO', label: 'LAMBUNAO' },
  { value: 'LEGANES', label: 'LEGANES' },
  { value: 'LEMERY', label: 'LEMERY' },
  { value: 'LEON', label: 'LEON' },
  { value: 'MAASIN', label: 'MAASIN' },
  { value: 'MIAGAO', label: 'MIAGAO' },
  { value: 'MINA', label: 'MINA' },
  { value: 'NEW LUCENA', label: 'NEW LUCENA' },
  { value: 'OTON', label: 'OTON' },
  { value: 'PASSI CITY', label: 'PASSI CITY' },
  { value: 'PAVIA', label: 'PAVIA' },
  { value: 'POTOTAN', label: 'POTOTAN' },
  { value: 'SAN DIONISIO', label: 'SAN DIONISIO' },
  { value: 'SAN ENRIQUE', label: 'SAN ENRIQUE' },
  { value: 'SAN JOAQUIN', label: 'SAN JOAQUIN' },
  { value: 'SAN MIGUEL', label: 'SAN MIGUEL' },
  { value: 'SAN RAFAEL', label: 'SAN RAFAEL' },
  { value: 'SANTA BARBARA', label: 'SANTA BARBARA' },
  { value: 'SARA', label: 'SARA' },
  { value: 'TIGBAUAN', label: 'TIGBAUAN' },
  { value: 'TUBUNGAN', label: 'TUBUNGAN' },
  { value: 'ZARRAGA', label: 'ZARRAGA' },
  { value: 'WVSU', label: 'WVSU' },
  { value: 'BETA', label: 'BETA' },
];

export default municipalityTypes
