const  schoolOptionTypes = [
  {
    label: 'ABE INTERNATIONAL BUSINESS COLLEGE-ILOILO',
    value: 'ABE INTERNATIONAL BUSINESS COLLEGE-ILOILO',
  },
  {
    label: 'ACLC COLLEGE OF ILOILO CITY, INC.',
    value: 'ACLC COLLEGE OF ILOILO CITY, INC.',
  },
  { label: 'ACSI COLLEGE OF ILOILO', value: 'ACSI COLLEGE OF ILOILO' },
  {
    label: 'AMA COMPUTER COLLEGE-ILOILO',
    value: 'AMA COMPUTER COLLEGE-ILOILO',
  },
  { label: 'CABALUM WESTERN COLLEGE', value: 'CABALUM WESTERN COLLEGE' },
  {
    label: 'CENTRAL PHILIPPINE UNIVERSITY',
    value: 'CENTRAL PHILIPPINE UNIVERSITY',
  },
  { label: 'COLEGIO DE SAN JOSE', value: 'COLEGIO DE SAN JOSE' },
  {
    label: 'COLEGIO DE SAGRADO CORAZON DE JESUS',
    value: 'COLEGIO DE SAGRADO CORAZON DE JESUS',
  },
  {
    label: 'DOMINICAN COLLEGE OF ILOILO',
    value: 'DOMINICAN COLLEGE OF ILOILO',
  },
  { label: 'GSEF COLLEGE, INC.', value: 'GSEF COLLEGE, INC.' },
  {
    label: 'HUA SIONG COLLEGE OF ILOILO',
    value: 'HUA SIONG COLLEGE OF ILOILO',
  },
  {
    label: 'ILOILO CITY COMMUNITY COLLEGE',
    value: 'ILOILO CITY COMMUNITY COLLEGE',
  },
  { label: "ILOILO DOCTORS' COLLEGE", value: "ILOILO DOCTORS' COLLEGE" },
  {
    label: "ILOILO DOCTORS' COLLEGE OF MEDICINE, INC",
    value: "ILOILO DOCTORS' COLLEGE OF MEDICINE, INC",
  },
  {
    label: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-DUMANGAS CAMPUS',
    value: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-DUMANGAS CAMPUS',
  },
  {
    label: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-LEON CAMPUS',
    value: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-LEON CAMPUS',
  },
  {
    label: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-MIAGAO CAMPUS',
    value: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-MIAGAO CAMPUS',
  },
  {
    label: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-BAROTAC NUEVO CAMPUS',
    value: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-BAROTAC NUEVO CAMPUS',
  },
  {
    label: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-MAIN',
    value: 'ILOILO SCIENCE AND TECHNOLOGY UNIVERSITY-MAIN',
  },
  {
    label: 'ILOILO STATE COLLEGE OF FISHERIES',
    value: 'ILOILO STATE COLLEGE OF FISHERIES',
  },
  {
    label: 'ILOILO STATE COLLEGE OF FISHERIES-BAROTAC NUEVO CAMPUS',
    value: 'ILOILO STATE COLLEGE OF FISHERIES-BAROTAC NUEVO CAMPUS',
  },
  {
    label: 'ILOILO STATE COLLEGE OF FISHERIES-DINGLE CAMPUS',
    value: 'ILOILO STATE COLLEGE OF FISHERIES-DINGLE CAMPUS',
  },
  {
    label: 'ILOILO STATE COLLEGE OF FISHERIES-DUMANGAS CAMPUS',
    value: 'ILOILO STATE COLLEGE OF FISHERIES-DUMANGAS CAMPUS',
  },
  {
    label: 'ILOILO SATE COLLEGE OF FISHERIES-SAN ENRIQUE CAMPUS',
    value: 'ILOILO SATE COLLEGE OF FISHERIES-SAN ENRIQUE CAMPUS',
  },
  {
    label:
      'INTEGRATED MIDWIVES ASSOCIATION OF THE PHILIPPINES FOUNDATION SCHOOL OF MIDWIFERY, INC.',
    value:
      'INTEGRATED MIDWIVES ASSOCIATION OF THE PHILIPPINES FOUNDATION SCHOOL OF MIDWIFERY, INC.',
  },
  { label: 'INTERFACE COMPUTER COLLEGE', value: 'INTERFACE COMPUTER COLLEGE' },
  {
    label: 'JOHN B. LACSON FOUNDATION MARITIME UNIVERSITY-MOLO, INC.',
    value: 'JOHN B. LACSON FOUNDATION MARITIME UNIVERSITY-MOLO, INC.',
  },
  {
    label: 'JOHN B.  LACSON FOUNDATION MARITIME UNIVERSITY (AREVALO), INC.',
    value: 'JOHN B.  LACSON FOUNDATION MARITIME UNIVERSITY (AREVALO), INC.',
  },
  {
    label: 'NEW LUCENA POLYTECHNIC COLLEGE',
    value: 'NEW LUCENA POLYTECHNIC COLLEGE',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-AJUY CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-AJUY CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-BATAD CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-BATAD CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-CONCEPTION CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-CONCEPTION CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-LEMERY CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-LEMERY CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-VICTORINO SALCEDO-CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-VICTORINO SALCEDO-CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-BAROTAC VIEJO CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-BAROTAC VIEJO CAMPUS',
  },
  {
    label: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-MAIN CAMPUS',
    value: 'NORTHERN ILOILO POLYTECHNIC STATE COLLEGE-MAIN CAMPUS',
  },
  { label: 'PASSI CITY COLLEGE', value: 'PASSI CITY COLLEGE' },
  {
    label: 'SANTA ISABEL COLLEGE OF ILOILO CITY',
    value: 'SANTA ISABEL COLLEGE OF ILOILO CITY',
  },
  {
    label: 'ST. ANNE COLLEGE OF ILOILO, INC.',
    value: 'ST. ANNE COLLEGE OF ILOILO, INC.',
  },
  { label: 'ST. PAUL UNIVERSITY ILOILO', value: 'ST. PAUL UNIVERSITY ILOILO' },
  { label: 'ST. THERESE-MTC COLLEGES', value: 'ST. THERESE-MTC COLLEGES' },
  {
    label: 'ST. THERESE-MTC COLLEGES TIGBAUAN',
    value: 'ST. THERESE-MTC COLLEGES TIGBAUAN',
  },
  {
    label: 'ST. THERESE- MTC COLLEGES-LA FIESTA SITE INC.',
    value: 'ST. THERESE- MTC COLLEGES-LA FIESTA SITE INC.',
  },
  {
    label: 'ST. VINCENT COLLEGE OF SCIENCE AND TECHNOLOGY',
    value: 'ST. VINCENT COLLEGE OF SCIENCE AND TECHNOLOGY',
  },
  {
    label: 'ST. VINCENT FERRER SEMINARY',
    value: 'ST. VINCENT FERRER SEMINARY',
  },
  { label: 'STI COLLEGE INC.', value: 'STI COLLEGE INC.' },
  { label: 'UNIVERSITY OF ILOILO', value: 'UNIVERSITY OF ILOILO' },
  { label: 'UNIVERSITY OF SAN AGUSTIN', value: 'UNIVERSITY OF SAN AGUSTIN' },
  {
    label: 'UNIVERSITY OF THE PHILIPPINES VISAYAS',
    value: 'UNIVERSITY OF THE PHILIPPINES VISAYAS',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-CALINOG CAMPUS',
    value: 'WEST VISAYAS STATE UNIVERSITY-CALINOG CAMPUS',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-JANIUAY CAMPUS',
    value: 'WEST VISAYAS STATE UNIVERSITY-JANIUAY CAMPUS',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-LAMBUNAO CAMPUS',
    value: 'WEST VISAYAS STATE UNIVERSITY-LAMBUNAO CAMPUS',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-POTOTAN CAMPUS',
    value: 'WEST VISAYAS STATE UNIVERSITY-POTOTAN CAMPUS',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-COLLEGE OF AGRICULTURE & FORESTRY',
    value: 'WEST VISAYAS STATE UNIVERSITY-COLLEGE OF AGRICULTURE & FORESTRY',
  },
  {
    label: 'WEST VISAYAS STATE UNIVERSITY-MAIN',
    value: 'WEST VISAYAS STATE UNIVERSITY-MAIN',
  },
  {
    label: 'WESTERN INSTITUTE OF TECHNOLOGY',
    value: 'WESTERN INSTITUTE OF TECHNOLOGY',
  },
  {
    label: 'ABBA Institute of Technology Incorporated',
    value: 'ABBA Institute of Technology Incorporated',
  },
  { label: 'Aklan Polytechnic College', value: 'Aklan Polytechnic College' },
];
export default  schoolOptionTypes 