const userIndustryOptionTypes = [
  '',
  '[A] Agriculture, forestry and fishing',
  '[B] Mining and quarrying',
  '[C] Manufacturing Electricity, gas, steam and air conditioning supply',
  '[D] Water supply; sewerage, waste management and remediation activities',
  '[E] Construction',
  '[F] Wholesale and retail trade',
  '[G] repair of motor vehicles and motorcycles',
  '[H] Transportation and storage',
  '[I] Accommodation and food service activities',
  '[J] Information and communication',
  '[K] Financial and insurance activities',
  '[L] Real estate activities',
  '[M] Professional, scientific and technical activities',
  '[N] Administrative and support service activities',
  '[O] Public administration and defense; compulsory social security',
  '[P] Education',
  '[Q] Human health and social work activities',
  '[R] Arts, entertainment and recreation',
  '[S] Other service activities',
  '[T] Activities of households as employers; undifferentiated goods-and services-producing activities of households for own use',
  '[U] Activities of extraterritorial organization and bodies',
];
export default userIndustryOptionTypes